### ISSUE TITLE
ngoi3 〔ŋɔːi˧〕→愛 撳唔出

### ISSUE THREAD

**Issue by David-H-1** [rime/rime-cantonese#101]
「愛」呢個字有兩個發音
ngoi3 同 oi3
oi3→愛　可以撳出
但係ngoi3 →愛 就唔可以
請更正，多謝！

**Comment by laubonghaudoi** [comment]
我哋嘅 README 上面寫咗「唔支持任何懶音同模糊音」，「愛」字本身就凈係得 oi3 一個發音。如果你想打 ngoi3 都出「愛」，可以按照README上面嘅步驟添加模糊音支援。
