### ISSUE TITLE
速成反查粵拼

### ISSUE THREAD

**Issue by CorgiCute96** [rime/rime-cantonese#102]
我本身有用開速成，有時會用粵拼反查

但係唔知點解反查link唔到去jyutping字典啲字，連音都唔啱
有無人幫下我？

![image](https://user-images.githubusercontent.com/74829984/99882320-7b2a9880-2c5a-11eb-9fdc-29a5dfe40b45.png)

**Comment by szc126** [comment]
Resolved at the Telegram group.
