### ISSUE TITLE
申請詞庫更正

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#108]
### 修改意見

| 字 | 音 | 出處／參考資料／備考 |
|----|----|:-------------------|
|宇晴匯|jyu cing wui|jyut6ping3.phrase.dict.yaml中第87588行的「宇晴滙」更正為「宇晴匯」，位於荔枝角深盛路9號|  
|    |    |                    |

**Comment by ayaka14732** [comment]
Thx~

**Comment by tiujejauci** [comment]
### 修改意見

| 字 | 音 | 出處／參考資料／備考 |
|----|----|:-------------------|
|采頤花園|coi ji faa jyun|jyut6ping3.phrase.dict.yaml中第135105行的「採頤花園」更正為「采頤花園」，位於新蒲崗彩虹道242號|
|採葉庭|coi jip ting|jyut6ping3.phrase.dict.yaml中第135080行的「採葉庭」更正為「采葉庭」，位於元朗舊墟路33號|

**Comment by laubonghaudoi** [comment]
可唔可以去上游詞表改？而家呢個碼表都唔接受直接修改嘅

**Comment by laubonghaudoi** [comment]
@tiujejauci 意思就係，呢度你數據你都唔使理，直接睇呢度上游詞表嘅就得 https://github.com/CanCLID/rime-cantonese-upstream
