### ISSUE TITLE
问题复杂化，完全就不知怎么配置。

### ISSUE THREAD

**Issue by lzwnei** [rime/rime-cantonese#110]
### 問題描述

问题复杂化，完全就不知怎么配置。连个安装文件都没有

**Comment by hfhchan** [comment]
安裝教程請參閲 https://github.com/rime/rime-cantonese/releases/tag/2021.01.19 ，下面附有適合不同用設置下嘅操作。

**Comment by hfhchan** [comment]
如果對於 rime 技術架構或者設置方式有意見，請於 https://github.com/rime/home/issues 回報。

**Comment by hfhchan** [comment]
如果對於 rime 對於附加語言設置方式有意見，請參與 rime/home#336 的討論，或於 https://github.com/rime/home/issues 回報新 issue.

**Comment by laubonghaudoi** [comment]
@lzwnei 可唔可以講詳細啲你嘅問題？

**Comment by lzwnei** [comment]
MAC 終端機 運行此命令沒有任何反應。
「curl -fsSL https://git.io/rime-install | bash -s -- cantonese emoji sgalal/rime-opencc-latest custom:set:config=default,key=installed_from,value=rime-cantonese custom:add:schema=jyut6ping3 lotem/rime-octagram-data ***@***.*** lotem/rime-octagram-data:customize:schema=jyut6ping3,model=hant」


進階方案完全不會用（不懂），還有關於「東風破 /plum/ 口令」的描述過於複雜（看得頭暈腦脹）以及沒有翻譯，亦無法安裝。



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2021年3月16日(週二) 凌晨0:38
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [rime/rime-cantonese] 问题复杂化，完全就不知怎么配置。 (#110)




 
@lzwnei 可唔可以講詳細啲你嘅問題？

**Comment by laubonghaudoi** [comment]
@lzwnei 點解你跑嘅命令入面會有個`***@***.***`？我哋嘅教程入面冇呢個嘢喎

**Comment by lzwnei** [comment]
我是直接複製貼上的，是不是有人改了你們不知道



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2021年3月16日(週二) 凌晨1:28
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [rime/rime-cantonese] 问题复杂化，完全就不知怎么配置。 (#110)




 
@lzwnei 點解你跑嘅命令入面會有個***@***.***？我哋嘅教程入面冇呢個嘢喎

**Comment by hfhchan** [comment]
*** 應該係因為用郵件回覆，疑似電郵地址會被 Github 改成*****.

**Comment by hfhchan** [comment]
> MAC 終端機 運行此命令沒有任何反應。

試試換個 VPN 試試？

**Comment by hfhchan** [comment]
> 進階方案完全不會用（不懂），還有關於「東風破 /plum/ 口令」的描述過於複雜（看得頭暈腦脹）以及沒有翻譯，亦無法安裝。

你係新安裝，定係本身已經用緊 RIME？

如果本身已經有 RIME，直接在 terminal 執行 `bash plum/rime-install cantonese` 就可以。

**Comment by hfhchan** [comment]
唔好意思，請問你不斷強調嘅 `问题复杂化，完全就不知怎么配置` `完全不會用（不懂）` `描述過於複雜（看得頭暈腦脹）` `沒有翻譯` 指嘅係睇唔明粵語，定係教程嘅粵語表達唔夠清晰？

**Comment by laubonghaudoi** [comment]
@lzwnei 可唔可以截個圖畀我哋睇下具體係咩反應？噉得個文字講我哋好難幫你診斷解決問題

**Comment by lzwnei** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/rime-cantonese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 上午8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rime/rime-cantonese] 问题复杂化，完全就不知怎么配置。 (#110)





  
進階方案完全不會用（不懂），還有關於「東風破 /plum/ 口令」的描述過於複雜（看得頭暈腦脹）以及沒有翻譯，亦無法安裝。
  
你係新安裝，定係本身已經用緊 RIME？
 
如果本身已經有 RIME，直接在 terminal 執行 bash plum/rime-install cantonese 就可以。

**Comment by lzwnei** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/rime-cantonese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rime/rime-cantonese] 问题复杂化，完全就不知怎么配置。 (#110)





 
@lzwnei 可唔可以截個圖畀我哋睇下具體係咩反應？噉得個文字講我哋好難幫你診斷解決問題

**Comment by lzwnei** [comment]
&nbsp;是否與M1晶片有關？不相容？







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rime/rime-cantonese"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 上午8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rime/rime-cantonese] 问题复杂化，完全就不知怎么配置。 (#110)





 
@lzwnei 可唔可以截個圖畀我哋睇下具體係咩反應？噉得個文字講我哋好難幫你診斷解決問題

**Comment by hfhchan** [comment]
@lzwnei 你試下跟呢個page安裝？

[新手安裝教程](https://github.com/rime/rime-cantonese/wiki/%E6%96%B0%E6%89%8B%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B-%EF%BC%88WIP%EF%BC%89)
