### ISSUE TITLE
想找一本地道廣州口語相關字典！傳統口語讀音！

### ISSUE THREAD

**Issue by tungmouse** [rime/rime-cantonese#113]
例如：希臘，應該讀 lip，

擸	lip3 顺着方向抚摸(一般指对狗、猫等顺毛 （1997年《广州话词典(简)》

請各位師兄推介！

**Comment by laubonghaudoi** [comment]
所有字音問題，都可以去 https://jyut.net/ 查。入面有齊晒所有常用漢字嘅粵語標準音。如果冇其他問題嘅話我就閂咗個 issue 嘞。

**Comment by tiujejauci** [comment]
亦都可以入 https://shyyp.net/hant 查讀音，同https://jyut.net/ 大致相同。
