### ISSUE TITLE
Installation of Waesel+Rime-Cantonese as a Chocolatey package

### ISSUE THREAD

**Issue by BrandonKMLee** [rime/rime-cantonese#114]
Problem: Currently if Waesel is installed using the current Chocolatey package, it will register Rime as a "Simplified, China" input method and not "Traditional, Hong Kong". This makes using the input method harder to use in the Cantonese context.

See: https://community.chocolatey.org/packages/weasel and https://github.com/chtof/chocolatey-packages/tree/master/automatic/weasel

**Comment by ayaka14732** [comment]
Hi, @BrandonKMLee, we are not the maintainers of the Chocolatey package. Please report this issue to @chtof.

**Comment by laubonghaudoi** [comment]
@BrandonKMLee This seems to be an issue of the weasel software, not rime-cantonese. Please open an issue for this in the https://github.com/rime/weasel repository. If there isn't anything else, please close this issue.

**Comment by BrandonKMLee** [comment]
@laubonghaudoi the Weasel team may treat this as a locality issue, judging by their issues page being mainly in Simplified Chinese. Other than that, the Chocolatey package maintainer @chtof can be contacted but their issues page operates in slightly different ways. It is best to mark notes on Hong Kong and Taiwan l10n issues in a separate place first.

**Comment by sgalal** [comment]
The rime architecture contains mainly 3 parts:

1) front end: weasel (Windows), squrriel (macOS), ibus-rime, fcitx-rime, fcitx5-rime (Linux), etc
2) back end: librime
3) schemata: rime-luna-pinyin, rime-cantonese, etc

The schemata (in this case, rime-cantonese) and front ends (in this case, weasel) are seperate modules. So this is the wrong place to report this issue.

Solution: Wait for https://github.com/rime/weasel/issues/438 to be resolved first. Then report an issue to the Chocolatey package maintainer.

**Comment by Raymonf** [comment]
@BrandonKMLee The Chocolatey package is here: https://github.com/chtof/chocolatey-packages/tree/master/automatic/weasel

You can open an issue there. I believe it is possible to automate this on unattended installs with unattend.xml, if that's your use case.
