### ISSUE TITLE
Question: How to get typing with tones working?

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [rime/rime-cantonese#115]
### 問題描述
I am using rime-cantonese with Ibus on Arch Linux. It works so far, however the [README.md typing animation](https://github.com/rime/rime-cantonese/blob/master/demo/tone.gif) seems to indicate that entering tones is possible too. I have added to the default.custom.yaml the following:

```
patch:
  schema_list:
    - schema: jyut6ping3
```
When I try to type "jyut6ping3", it does not work as in the animation, because typing '6' and '3' selects the corresponding Ibus suggestion. How can I get it work so that I can enter the tones 6 and 3 by typing "jyut6ping3"?

### 修改意見

| 字 | 音 | 出處／參考資料／備考 |
|----|----|:-------------------|
| 例 |lai6| 《廣韻》力制切。     |  
|    |    |                    |

**Comment by ayaka14732** [comment]
Hi, @ChristophSchmidpeter. The question is already answered here: https://github.com/rime/rime-cantonese/blob/master/README-en.md#tonal-markers

**Comment by ChristophSchmidpeter** [comment]
@ayaka14732 Thanks! Somehow I've missed that section. It works fine now
