### ISSUE TITLE
粵語輸入法BUG

### ISSUE THREAD

**Issue by Yiulapwai** [rime/rime-cantonese#119]
粵語輸入法不能準確地根據用户所輸入的粵拼提供其所想輸入的“zi”
例如： zi = 字 （沒有此字）
faat = 法 （沒有此字）

<img width="115" alt="Screenshot 2021-05-16 at 13 29 09" src="https://user-images.githubusercontent.com/73850215/118395454-d5754680-b64a-11eb-993d-866fcc6d8d3e.png">
<img width="122" alt="Screenshot 2021-05-16 at 13 29 14" src="https://user-images.githubusercontent.com/73850215/118395458-d6a67380-b64a-11eb-84e6-8e885e8c4ba5.png">
<img width="120" alt="Screenshot 2021-05-16 at 13 29 20" src="https://user-images.githubusercontent.com/73850215/118395459-d73f0a00-b64a-11eb-9efa-282070317da9.png">
<img width="118" alt="Screenshot 2021-05-16 at 13 29 25" src="https://user-images.githubusercontent.com/73850215/118395460-d7d7a080-b64a-11eb-9b43-0ec0ee5127a4.png">
<img width="122" alt="Screenshot 2021-05-16 at 13 29 30" src="https://user-images.githubusercontent.com/73850215/118395461-d8703700-b64a-11eb-9832-9b88f1f2cc18.png">
<img width="114" alt="Screenshot 2021-05-16 at 13 29 34" src="https://user-images.githubusercontent.com/73850215/118395462-d8703700-b64a-11eb-9894-50ad9164a9fb.png">
<img width="113" alt="Screenshot 2021-05-16 at 13 29 39" src="https://user-images.githubusercontent.com/73850215/118395463-d908cd80-b64a-11eb-9a35-7b987271ee9c.png">
<img width="113" alt="Screenshot 2021-05-16 at 13 29 43" src="https://user-images.githubusercontent.com/73850215/118395464-d908cd80-b64a-11eb-8c75-640b396f25a2.png">
<img width="109" alt="Screenshot 2021-05-16 at 13 29 47" src="https://user-images.githubusercontent.com/73850215/118395466-d9a16400-b64a-11eb-8ed8-f39fe2d9acae.png">

<img width="158" alt="Screenshot 2021-05-16 at 13 30 31" src="https://user-images.githubusercontent.com/73850215/118395477-ea51da00-b64a-11eb-92f4-583c3cab3935.png">

**Comment by ososoio** [comment]
Hi @Yiulapwai 

請問你個輸入法程式係點樣安裝嘅？用嘅係唔係呢度(rime-cantonese)嘅碼表，Rime方案係唔係 `jyut6ping3`？

**Comment by laubonghaudoi** [comment]
![image](https://user-images.githubusercontent.com/11172180/118405778-2b87c100-b62e-11eb-82cf-7b0d2eee5c6f.png)
![image](https://user-images.githubusercontent.com/11172180/118405795-49edbc80-b62e-11eb-825f-d8035f1b0a73.png)
@Yiulapwai 我呢便就冇任何問題，我都想問你係點裝嘅呢？

**Comment by tanxpyox** [comment]
如果單字輸入嘅話建議配合聲調輸入，例如

`ziqq` :
![image](https://user-images.githubusercontent.com/9696140/118451087-733e4380-b727-11eb-9ae6-3f77c14f4b4c.png)

`faatq`:
![image](https://user-images.githubusercontent.com/9696140/118451118-7cc7ab80-b727-11eb-94fc-66182027aa49.png)

**Comment by laubonghaudoi** [comment]
鑑於 @Yiulapwai 太耐冇覆，暫時閂咗呢個 issue 先，如果覺得有必要可以重新開返
