### ISSUE TITLE
Character style (Simplified / Traditional) is not persistent

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [rime/rime-cantonese#120]
### 問題描述
The character style is forgotten upon switching between input languages. 

Steps to reproduce
- Set Simplified characters (i.e. 大陸簡化刊字) in Rime-Cantonese
- Switch to another input language (E.g. to a US / GER etc. keyboard)
- Switch back to Rime-Cantonese
- Note that typing produces Traditional characters again
- Note that in contrast the Simpified / Traditional character setting is persistent when using other Rime input methods (E.g. rime-terra-pinyin)

**Comment by ChristophSchmidpeter** [comment]
How can I change the label to "bug"?

**Comment by laubonghaudoi** [comment]
@tanxpyox 我記得呢個唔係bug嚟嘅？係我哋專登整嘅，儘量等大家用返繁體打粵文。

@ChristophSchmidpeter This is not a bug. We set this intentionally. Simplified Chinese characters is a writing system tailored for Mandarin. It is not suitable for writing non-Mandarin languages. We recommend everybody to write Cantonese with traditional characters.

If you insist to change it to simplified characters permanently, change [this line](https://github.com/rime/rime-cantonese/blob/1168d4ca475656748938475ca5d96e41096d8b5a/jyut6ping3.schema.yaml#L41) into `reset: 0` in your schema.

**Comment by tanxpyox** [comment]
Hi Christoph. The change is indeed intentional as most Cantonese-only characters are undefined in the simplified character set. 

As @laubonghaudoi suggests, changing line 41 in the schema to `reset: 0` will resolve the problem.

**Comment by ChristophSchmidpeter** [comment]
@laubonghaudoi & @tanxpyox: Thanks for the info! I have tried settting `reset: 0` in the file $home/.config/ibus/rime/build/jyut6ping3.schema.yaml
and performed "sync" and "deploy". However, it is still not persistent. (I've also tried changing setting it in /usr/share/rime-data/jyut6ping3.schema.yaml)
Not sure what I'm doing wrong. So setting `reset: 0` have the effect of making it persistent on your systems, right?

**Comment by tanxpyox** [comment]
Oh my apologies - could you try removing the reset line altogether?

**Comment by ChristophSchmidpeter** [comment]
@tanxpyox : removing the reset line worked for me. Thank you!!
I'm surprised though that `reset: 0` has a different behaviour than removing the line. Is this intended behaviour?

**Comment by ChristophSchmidpeter** [comment]
I think adding a comment "Uncomment the following line to persist the character style" or sth. like that before the `reset: 1` line might be helpful for people having the same intention.

**Comment by tanxpyox** [comment]
> I'm surprised though that `reset: 0` has a different behaviour than removing the line. Is this intended behaviour?

Yes, I forgot that `reset: 0` actually meant reverting the settings to the 'first' character set (Traditional Chinese).

> I think adding a comment "Uncomment the following line to persist the character style" or sth. like that before the `reset: 1` line (and maybe in the README) might be helpful for people having the same intention.

Good idea!
