### ISSUE TITLE
我有詞條想請求加入

### ISSUE THREAD

**Issue by ososoio** [rime/rime-cantonese#123]
大家好！我手頭有 100 條詞條想加入來，但因爲我唔知加咗之後點樣將 `jyut6ping3.dict.yaml` 排序，所以唔創建 PR 嘞。

呢啲詞條全部都係 粵拼輸入法App 收到嘅用家建議/回報，原文我放咗喺呢度： https://github.com/ososoio/user-lexicon/blob/master/patches/2021-06-30.yaml

**Comment by ososoio** [comment]
做個表格供查閱：


| 詞彙                 | Jyutping                                         |
|----------------------|--------------------------------------------------|
| 白左                 | baak6 zo2                                        |
| 簽走                 | cim1 zau2                                        |
| 潮汕佬               | ciu4 saan3 lou2                                  |
| 潮州府               | ciu4 zau1 fu2                                    |
| 潮州佬               | ciu4 zau1 lou2                                   |
| 滄海一聲笑           | cong1 hoi2 jat1 sing1 siu3                       |
| 川普                 | cyun1 pou2                                       |
| 大統領               | daai6 tung2 ling5                                |
| 等角螺線             | dang2 gok3 lo4 sin3                              |
| 對數螺線             | deoi3 sou3 lo4 sin3                              |
| 的盧                 | dik1 lou4                                        |
| 的顱                 | dik1 lou4                                        |
| 杜林普               | dou6 lam4 pou2                                   |
| 反油酸               | faan2 jau4 syun1                                 |
| 反式油酸             | faan2 sik1 jau4 syun1                            |
| 反智                 | faan2 zi3                                        |
| 反智主義             | faan2 zi3 zyu2 ji6                               |
| 反中亂港             | faan2 zung1 lyun6 gong2                          |
| 費拉                 | fai3 laai1                                       |
| 費拉不堪             | fai3 laai1 bat1 ham1                             |
| 分韻撮要             | fan1 wan6 cyut3 jiu3                             |
| 噉又未必             | gam2 jau6 mei6 bit1                              |
| 記錯                 | gei3 co3                                         |
| 極右                 | gik6 jau6                                        |
| 極左                 | gik6 zo2                                         |
| 劍神                 | gim3 san4                                        |
| 劍聖                 | gim3 sing3                                       |
| 毽球                 | gin3 kau4                                        |
| 高州府               | gou1 zau1 fu2                                    |
| 高州佬               | gou1 zau1 lou2                                   |
| 虢礫緙嘞             | gwik1 lik1 kaak1 laak1                           |
| 廣東佬               | gwong2 dung1 lou2                                |
| 廣西佬               | gwong2 sai1 lou2                                 |
| 廣州府               | gwong2 zau1 fu2                                  |
| 廣州佬               | gwong2 zau1 lou2                                 |
| 客家佬               | haak3 gaa1 lou2                                  |
| 黑命貴               | hak1 ming6 gwai3                                 |
| 可防可控             | ho2 fong4 ho2 hung3                              |
| 香港佬               | hoeng1 gong2 lou2                                |
| 海南佬               | hoi2 naam4 lou2                                  |
| 疑犯追蹤             | ji4 faan2 zeoi1 zung1                            |
| 疑犯追蹤             | ji4 faan6 zeoi1 zung1                            |
| 毽球                 | jin2 kau4                                        |
| 羊角                 | joeng4 gok3                                      |
| 羊角地鐵             | joeng4 gok3 dei6 tit3                            |
| 羊角螺線             | joeng4 gok3 lo4 sin3                             |
| 圓外螺線             | jyun4 ngoi6 lo4 sin3                             |
| 圓內螺線             | jyun4 noi6 lo4 sin3                              |
| 粵語鍵盤             | jyut6 jyu5 gin6 pun2                             |
| 粵語鍵盤             | jyut6 jyu5 gin6 pun4                             |
| 粵語輸入法           | jyut6 jyu5 syu1 jap6 faat3                       |
| 粵拼鍵盤             | jyut6 ping3 gin6 pun2                            |
| 粵拼鍵盤             | jyut6 ping3 gin6 pun4                            |
| 粵拼輸入法           | jyut6 ping3 syu1 jap6 faat3                      |
| 越秀前               | jyut6 sau3 cin4                                  |
| 瓊州府               | king4 zau1 fu2                                   |
| 李將軍               | lei5 zoeng1 gwan1                                |
| 叻叻豬               | lek1 lek1 zyu1                                   |
| 雷州府               | leoi4 zau1 fu2                                   |
| 廉州                 | lim4 zau1                                        |
| 廉州府               | lim4 zau1 fu2                                    |
| 萬水千山總是情       | maan6 seoi2 cin1 saan1 zung2 si6 cing4           |
| 文化馬克思           | man4 faa3 maa5 hak1 si1                          |
| 文化馬克思主義       | man4 faa3 maa5 hak1 si1 zyu2 ji6                 |
| 文化馬克思主義陰謀論 | man4 faa3 maa5 hak1 si1 zyu2 ji6 jam1 mau4 leon6 |
| 民主自由             | man4 zyu2 zi6 jau4                               |
| 武德充沛             | mou5 dak1 cung1 pui3                             |
| 你係話               | nei5 hai6 waa6                                   |
| 五毒俱全             | ng5 duk6 keoi1 cyun4                             |
| 艾瑞卡               | ngaai6 seoi6 kaa1                                |
| 外擺線               | ngoi6 baai2 sin3                                 |
| 內擺線               | noi6 baai2 sin3                                  |
| 愛國愛港             | oi3 gwok3 oi3 gong2                              |
| 平上去入             | ping4 soeng5 heoi3 jap6                          |
| 頗似                 | po2 ci5                                          |
| 普通話拼音           | pou2 tung1 waa2 ping3 jam1                       |
| 普通話拼音           | pou2 tung1 waa6 ping3 jam1                       |
| 三拼                 | saam1 ping3                                      |
| 思源                 | si1 jyun4                                        |
| 思源黑體             | si1 jyun4 hak1 tai2                              |
| 思源明朝體           | si1 jyun4 ming4 ciu4 tai2                        |
| 思源明體             | si1 jyun4 ming4 tai2                             |
| 思源宋體             | si1 jyun4 sung3 tai2                             |
| 思源字體             | si1 jyun4 zi6 tai2                               |
| 韶州                 | siu4 zau1                                        |
| 韶州府               | siu4 zau1 fu2                                    |
| 肇慶府               | siu6 hing3 fu2                                   |
| 肇慶佬               | siu6 hing3 lou2                                  |
| 雙曲螺線             | soeng1 kuk1 lo4 sin3                             |
| 蘇爾科夫             | sou1 ji5 fo1 fu1                                 |
| 蘇姿丰               | sou1 zi1 fung1                                   |
| 惠州府               | wai6 zau1 fu2                                    |
| 惠州佬               | wai6 zau1 lou2                                   |
| 永漢路               | wing5 hon3 lou6                                  |
| 黃皮白左             | wong4 pei4 baak6 zo2                             |
| 智械                 | zi3 haai6                                        |
| 智械叛亂             | zi3 haai6 bun6 lyun6                             |
| 自由民主             | zi6 jau4 man4 zyu2                               |
| 直角引號             | zik6 gok3 jan5 hou6                              |
| 主權民主             | zyu2 kyun4 man4 zyu2                             |

**Comment by laubonghaudoi** [comment]
辛苦晒你，我等陣加落去

**Comment by ososoio** [comment]
@laubonghaudoi 

> 順便問下，隻輸入法仲有冇其他碼表入面冇嘅詞？我可以順便一次過加晒

冇嘞，隻App本身冇收集任何嘢

**Comment by hfhchan** [comment]
@laubonghaudoi 有啲本身 trunk 已經有，你睇睇先

**Comment by laubonghaudoi** [comment]
啱先嘅提交 https://github.com/rime/rime-cantonese/commit/346b7524e708b1cb7e2a673f84cd06479667b902 加咗，你哋睇下有冇問題，冇嘅話就可以閂咗呢個 issue 嘞
