### ISSUE TITLE
如何停用個別單字繁簡轉換？

### ISSUE THREAD

**Issue by lotc** [rime/rime-cantonese#133]
你好，我想問下有冇方法可以唔轉換某啲單字嘅簡體？
比如「係」字
例如書面語「我是陳小明，我在中大讀中文系。」
正體會寫成「我係陳小明，我喺中大讀中文系。」
但係簡體情況下，第一個「係」會變成「系」。
請問有冇方法可以停用某啲字嘅繁簡轉換呢？

我[查咗一下](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/Rime_description.md)，`simplifier` 下嘅有 `excluded_types` 呢個參數，但係寫得唔夠清楚，可否給出一個範例？
謝謝！

**Comment by laubonghaudoi** [comment]
呢個本身就係簡化字方案嚟嘅，簡化字方案入面冇「係喺繫」字，所以要打「係喺繫」只能夠切換返繁體字打（所以我哋唔推薦用簡化字打粵文）。用`excluded_types`限定轉化我未試過，要問下 @ayaka14732 更加熟悉啲

**Comment by ayaka14732** [comment]
簡化字嘅規範係《[通用規範漢字表](https://zh.wikisource.org/wiki/%E9%80%9A%E7%94%A8%E8%A7%84%E8%8C%83%E6%B1%89%E5%AD%97%E8%A1%A8)》，可以睇到簡化字冇「係」字，「係」簡化作「系」，所以「系」係啱嘅

`excluded_types` 我都唔熟

**Comment by lotc** [comment]
@laubonghaudoi 暫時用[修改 TPCharacters.txt](https://github.com/rime/home/issues/420) 嘅方法。
@ayaka14732 原來係咁嘅。多謝指正！
