### ISSUE TITLE
「㗎」嘅讀音係咪gaa3？

### ISSUE THREAD

**Issue by AlienKevin** [rime/rime-cantonese#138]
### 問題描述

「㗎」而家嘅讀音係ga3，但係我睇咗粵典同埋維基字典，發現佢哋都標註嘅係gaa3。

### 修改意見

| 字 | 音 | 出處／參考資料／備考 |
|----|----|:-------------------|
| 㗎 | gaa3 | 粵典 |  
|  㗎  |  gaa3  |  [維基字典](https://en.wiktionary.org/wiki/%E3%97%8E)   |

廣東話唔係我嘅母語，講嘅嘢有啲錯漏之處請大家指出🙏

**Comment by hfhchan** [comment]
請參閲香港語言學學會粵拼專題頁 https://www.lshk.org/jyutping 最底關於新增 a 同 oet 嘅腳注。

**Comment by hfhchan** [comment]
簡單來講，講嘢嘅時候，句末嘅語氣詞喺某啲情況唔會成個 aa 發出來。例如「係㗎喇噃」嘅實際發音係 hai6-ga3-la3-bo3，如果發成 hai6-gaa3-laa3-bo3 就會聽落好唔自然。

「a」係 2018 年先增加入去粵拼嘅，所以網上大部份資料都未更新。

**Comment by hfhchan** [comment]
簡單來講，講嘢嘅時候，句末嘅語氣詞喺某啲情況唔會成個 aa 發出來。例如「係㗎喇噃」嘅實際發音係 hai6-ga3-la3-bo3，如果發成 hai6-gaa3-laa3-bo3 就會聽落好唔自然。

「a」係 2018 年先增加入去粵拼嘅，所以網上大部份資料都未更新。

**Comment by AlienKevin** [comment]
明白咗，多謝！

**Comment by hfhchan** [comment]
(平時普通話嘅「明白了」粵語會講「明喇」「明晒」或者「原來係噉」，而唔會講「明白咗」)
