### ISSUE TITLE
jyut6ping3.phrase.dict.yaml需要改進

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#149]
### 問題描述

jyut6ping3.phrase.dict.yaml

### 修改意見

|錯字屋苑名|錯字位置|正確屋苑名|出處／參考資料|
|----|----|----|:-------------------|
|採頤花園|第135105列|采頤花園|香港九龍黃大仙區新蒲崗太子道東同彩虹道242號，詳見[維基百科](https://zh-yue.wikipedia.org/wiki/%E9%87%87%E9%A0%A4%E8%8A%B1%E5%9C%92)|
|採葉庭|第135080列|采葉庭|香港元朗舊墟路33號，詳見[維基百科](https://zh.wikipedia.org/zh-hk/%E9%87%87%E8%91%89%E5%BA%AD)|
|採金樓|135102列|彩金樓|太子道西102號[Google地圖](https://www.google.com/maps/place/%E9%A6%99%E6%B8%AF%E5%A4%AA%E5%AD%90%E5%A4%AA%E5%AD%90%E9%81%93%E8%A5%BF102%E8%99%9F%E5%BD%A9%E9%87%91%E6%A8%93/data=!4m2!3m1!1s0x340400b62584734d:0x8d3e071e48c59abe?sa=X&ved=2ahUKEwj1y5jd-Kz3AhUot1YBHQ_UCDoQ8gF6BAgJEAE)

還有就係:入邊食物類嘅「麪」要唔要轉做「麵」？

**Comment by tiujejauci** [comment]
[google地圖](https://www.google.com/search?newwindow=1&tbs=lf:1,lf_ui:2&tbm=lcl&sxsrf=APq-WBtpDcnYIll4OpIW7Uj7MFP3qOJ59w:1650783813648&q=%E9%87%87%E9%A0%A4%E8%8A%B1%E5%9C%92&rflfq=1&num=10&ved=2ahUKEwiFxMD2kKz3AhXbmVYBHd0bBuQQjGp6BAgFEAE#rlfi=hd:;si:;mv:[[22.3378347,114.20352190000001],[22.3342943,114.2007738]];tbs:lrf:!1m4!1u3!2m2!3m1!1e1!1m4!1u2!2m2!2m1!1e1!2m1!1e2!2m1!1e3!3sIAE,lf:1,lf_ui:2)

**Comment by tiujejauci** [comment]
https://github.com/rime/rime-cantonese/pull/150#issue-1213679339

**Comment by tiujejauci** [comment]
https://github.com/rime/rime-cantonese/pull/150

**Comment by laubonghaudoi** [comment]
而家所有嘅詞條改動都放喺上游詞表，唔該喺呢度改 https://github.com/CanCLID/rime-cantonese-upstream

**Comment by tiujejauci** [comment]
> [#150 ](https://github.com/rime/rime-cantonese/pull/150)

https://github.com/rime/rime-cantonese/files/8549934/jyut6ping3.phrase.dict.yaml.txt

**Comment by laubonghaudoi** [comment]
@tiujejauci  唔該喺個上游詞表度改，對呢個碼表嘅直接修改都會關閉。

**Comment by tiujejauci** [comment]
唔整喇

**Comment by graphemecluster** [comment]
> 唔該喺個上游詞表度改，對呢個碼表嘅直接修改都會關閉。

個問題似乎係上游詞表而家剩係管 chars 同 words 兩個 file，lettered、phrase 同 maps 仍然係要喺度改
