### ISSUE TITLE
习惯用简体中文，但系默任系繁体中文，有冇办法可以设置默任为简体中文

### ISSUE THREAD

**Issue by ColinWorld** [rime/rime-cantonese#151]
习惯用简体中文，但系默任系繁体中文，有冇办法可以设置默任为简体中文

**Comment by ososoio** [comment]
Hi @ColinWorld 

可以修改 `jyut6ping3.schema.yaml`

https://github.com/rime/rime-cantonese/blob/ba1f08242b4fd24494c5e0e5c527732e1b0d565e/jyut6ping3.schema.yaml#L37-L43

**Comment by laubonghaudoi** [comment]
個標題係用普通話拼音打嘅？「默任」好搞笑
