### ISSUE TITLE
 懷疑因電腦os是簡體導致無法正常打粵語拼音

### ISSUE THREAD

**Issue by SweetHome520** [rime/rime-cantonese#152]
電腦os是簡體，可加繁體但沒法改為繁體系統

想打繁體粵
但選字步驟 '粵語拼音'選項中
'粵'字顯示亂碼
亦沒法正常打粵語拼音
應該是國語或普通話拼音打出的中文
求解決方法，謝謝

**Comment by hfhchan** [comment]
我哋需要多啲資料先判斷到出咗咩問題：
1) 用緊咩系統？Windows 定係 macOS？
2) 用咩方法安裝？安裝包 (exe/pkg) 定手動？
3) 可否截圖你話出亂碼嗰版？

**Comment by SweetHome520** [comment]
1. window 10 
2. https://rime.im/官方下載，git下載zip，手動copyv 9 個yaml檔案到RIME
3.
![rime](https://user-images.githubusercontent.com/104655055/166094529-8149a5b5-749d-4232-9b78-2e3d8e531589.png)

**Comment by hfhchan** [comment]
Rime 係支援唔同語言嘅輸入法，朙月 (即明月) 係一個普通話嘅輸入方案

要裝粵拼，請依照下面網址嘅第二步設定：
https://github.com/rime/rime-cantonese/wiki/Windows-%E9%80%B2%E9%9A%8E%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B-(%E8%A6%96%E8%A6%BA%E7%95%8C%E9%9D%A2)

**Comment by laubonghaudoi** [comment]
@SweetHome520 你拉到下面見唔見得到「粵語拼音」呢個選項？

**Comment by SweetHome520** [comment]
唔該唔該 我再試試

**Comment by SweetHome520** [comment]
> @SweetHome520 你拉到下面見唔見得到「粵語拼音」呢個選項？之前無 我重裝window繁體之後搞掂咗啦 唔該晒咁多位

**Comment by hfhchan** [comment]
你話裝到噉我 close issue 先喇。

BTW，如果你用緊 iOS 手機，可以考慮埋安裝 Cantoboard 或者 Jyutping Keyboard。

如果喺國內用緊 Android 手機，亦可以下載搜狗輸入法再揀選粵拼。搜狗粵拼嘅詞庫部份源自本項目。
