### ISSUE TITLE
jyut6ping3.chars.dict.yaml causes WeaselDeployer.exe to crash

### ISSUE THREAD

**Issue by konzertnr9** [rime/rime-cantonese#154]
With 12 May 2022 version of jyut6ping3.chars.dict.yaml, WeaselDeployer.exe crashes with a 0xC0000409 error  on re-deployment.
jyut6ping3.table.bin is generated with a size of 199MB and all 0x00 content, disabling Cantonese input after the crash.

**Comment by laubonghaudoi** [comment]
可唔可以畀個具體啲嘅描述？係邊個版本嘅開始崩壞，邊個舊版仲係得嘅？

**Comment by konzertnr9** [comment]
2022年5月5號嗰版冇事，5月12號嗰版出事

**Comment by laubonghaudoi** [comment]
可唔可以試下5月11日嗰版有冇事？喺呢度 https://github.com/rime/rime-cantonese/tree/9a0f7abb239c472b48d335d4f45aa448c9e6533e

**Comment by konzertnr9** [comment]
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
 <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-05-15T01:33:49.8178050Z" /> 
  <EventRecordID>86331</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="43188" ThreadID="0" /> 
  <Channel>Application</Channel> 
  <Computer>PC005</Computer> 
  <Security /> 
  </System>
  <EventData>
  <Data>WeaselDeployer.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5d0e4f49</Data> 
  <Data>WeaselDeployer.exe</Data> 
  <Data>0.0.0.0</Data> 
  <Data>5d0e4f49</Data> 
  <Data>c0000409</Data> 
  <Data>00032131</Data> 
  <Data>99a8</Data> 
  <Data>01d867fbc456614e</Data> 
  <Data>C:\Program Files (x86)\Rime\weasel-0.14.3\WeaselDeployer.exe</Data> 
  <Data>C:\Program Files (x86)\Rime\weasel-0.14.3\WeaselDeployer.exe</Data> 
  <Data>c72d6308-603a-4ff0-956d-a6204f090ccd</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by Raymonf** [comment]
我依家就用緊5月11日嗰版，用得。

**Comment by konzertnr9** [comment]
用到
