### ISSUE TITLE
(schema)建議以WASDZ作爲筆畫輸入鍵位

### ISSUE THREAD

**Issue by ososoio** [rime/rime-cantonese#155]
而家筆畫輸入係以「橫豎撇捺折」嘅普通話拼音首字母 hspnz 作爲鍵位。

我建議改成 橫w、豎s、撇a、點d、折z。

理由：
1. w, s, d, z 係「橫 豎 點 折」嘅粵拼首字母。
2. 用 a 代表撇，係因爲佢喺 wsdz 左邊。
3. WASD 係常見嘅方向鍵，同筆畫方向有相似之處，唔會反直覺。
4. WASDZ 喺鍵盤相鄰位置，撳起身方便。

除咗 wasdz，當然仲可以兼容埋原來嘅 hspnz，或者再考慮埋英文。

我做咗個表格：

| 筆畫    | 鍵位      | 粵語       | 普通話      | 英語       |
|--------|----------|-----------|------------|------------|
| 橫     | W, H     | waang     | heng       | Horizontal |
| 豎     | S, V     | syu       | shu        | Vertical   |
| 撇     | A, P, L  | pit       | pie        | Left       |
| 點/捺   | D, N, R  | dim, naat | dian, na   | Right, Dot |
| 折     | Z, T     | zit       | zhe        | Turning    |

或者仲應該考慮埋各個系統自帶筆畫輸入法嘅鍵位，呢層我唔熟悉。

我做緊嘅 iOS、macOS 粵拼輸入法，會使用同樣嘅鍵位，噉樣啲用戶喺唔同程式可以有相似體驗。

我唔熟 Regex 同 Schema，唔知點改，所以提下建議，留待各位高手實現啦。

**Comment by laubonghaudoi** [comment]
呢個好似唔關 rime-cantonese事？係咪要改 rime 先得

**Comment by ososoio** [comment]
@laubonghaudoi 

我唔係好清楚 Rime Schema 係點樣工作嘅。
如果冇辦法通過`jyut6ping3.schema.yaml`改，可能要 fork [`rime-stroke`](https://github.com/rime/rime-stroke) 來改。噉就有啲大費周章，唔係好值得。

**Comment by laubonghaudoi** [comment]
rime-cantonese 本身係冇筆畫輸入法嘅定義嘅，凈係引用 rime 自帶嘅筆畫輸入法，所以我覺得應該係要台 rime-stroke
