### ISSUE TITLE
點樣設置默認爲簡體中文，而家每一次切換應用或者restart電腦都要使用Ctrl+`來設置，好麻煩

### ISSUE THREAD

**Issue by ColinWorld** [rime/rime-cantonese#156]
點樣設置默認爲簡體中文，而家每一次切換應用或者restart電腦都要使用Ctrl+`來設置，好麻煩

**Comment by ososoio** [comment]
睇睇 https://github.com/rime/rime-cantonese/issues/151#issuecomment-1112183082
