### ISSUE TITLE
M1 Mac WhatsApp 轉唔到 Squirrel 輸入法打字

### ISSUE THREAD

**Issue by tsokawing** [rime/rime-cantonese#157]
喺 WhatsApp 入面轉做 Squirrel 會自動彈返上一個用緊嘅輸入法

我用緊嘅係：
Squirrel 0.15.2
WhatsApp Desktop 2.2216.8
MacOS Monterey 12.2.1

https://user-images.githubusercontent.com/97432858/170000796-e3c988b1-1262-460f-bf79-dc9b893f7902.mov

**Comment by hfhchan** [comment]
Squirrel 0.15.2
macOS Monterey 12.3.1
WhatsApp 2.2216.8

reproduce 唔到...

**Comment by hfhchan** [comment]
Update 個 macOS 試試？

**Comment by tsokawing** [comment]
更新到 macOS Monterey 12.4
解決咗，唔該曬

> Update 個 macOS 試試？

**Comment by hfhchan** [comment]
掂！
