### ISSUE TITLE
关于emoji

### ISSUE THREAD

**Issue by y1rn** [rime/rime-cantonese#162]
###  请问可唔可以整翻个cantonese emoji

我嘅rime安装咗emoji。睇咗吓rime_emoji嘅档，比较少广东话嘅mapping，平时打广东话基本上用唔着。请问有冇打算或者可唔可以整翻个cantonese版嘅emoji

**Comment by ososoio** [comment]
Hi @y1rn 

我有喺度做緊 emoji-cantonese，尚未做完。
https://github.com/ososoio/emoji-cantonese

**Comment by laubonghaudoi** [comment]
喺 @ososoio 整好之前我哋係唔係都可以將佢整合入 rime-cantonese入面？

**Comment by ososoio** [comment]
@laubonghaudoi 

我覺得可以。係咪喺呢度開 PR，而唔係上游 rime-cantonese-upstream 呢？

**Comment by laubonghaudoi** [comment]
冇錯，直接改呢度個`schema.yaml`就得
