### ISSUE TITLE
有關「𧒽」字

### ISSUE THREAD

**Issue by fei0316** [rime/rime-cantonese#170]
### 問題描述

希望可以加入呢個字，唔知道喺呢度提出請求啱唔啱？呢個字既用嚟表示黃沙蜆，亦係佛山嘅一個公園同地鐵站嘅名[（參考）](https://zh.wikipedia.org/wiki/%F0%A7%92%BD%E5%B4%97%E7%AB%99)。

### 修改意見

應該加入呢個字，讀音應該係 leoi1，主要參考[呢個網站](https://jyut.net/query?q=%F0%A7%92%BD)同上面嘅維基條目。

| 字 | 音 | 出處／參考資料／備考 |
|----|----|:-------------------|
| 𧒽 |leoi1|  粵語同音字典（增訂本）、廣州話標準音字彙、粵語同音字典 、英華分韻撮要     |

**Comment by ososoio** [comment]
Hi @fei0316 

Rime-Cantonese 係有收「𧒽」字嘅。你打字嗰陣可能要翻頁到好後邊先睇到。

**Comment by ososoio** [comment]
本來亦有收「𧒽崗」嘅。參見 #100 。

可能係之前用 rime-cantonese-upstream 重構嗰陣漏咗。

**Comment by fei0316** [comment]
真係唔好意思，應該係我嘅 rime-cantonese 版本太舊，啱啱更新咗之後就有喇。至於「𧒽崗」，唔知有咩解決辦法？

**Comment by ososoio** [comment]
> 真係唔好意思，應該係我嘅 rime-cantonese 版本太舊，啱啱更新咗之後就有喇。至於「𧒽崗」，唔知有咩解決辦法？

「𧒽崗」暫時解決辦法：因爲 Rime 係可以記憶用戶輸入詞語嘅，你打 leoigong，揀完「𧒽」字再揀「崗」字，打多幾次，直到候選詞出現「𧒽崗」就得啦。

**Comment by fei0316** [comment]
呢個我知道，但如果想正式加入嘅話，我按照 #100 噉樣開個 pull request 係咪就得？

**Comment by ososoio** [comment]
@fei0316 

要去上游 https://github.com/CanCLID/rime-cantonese-upstream 開 PR

**Comment by fei0316** [comment]
明白，我有時間去睇睇！噉我就 close 咗呢個 issue 先。
