### ISSUE TITLE
小狼毫粵語不支持Windows 11 touch keyboard

### ISSUE THREAD

**Issue by lester1027** [rime/rime-cantonese#172]
現在如果希望用touch keyboard操作小狼毫粵語輸入的話，虛擬數字鍵無法顯示。謝謝。

**Comment by laubonghaudoi** [comment]
觸摸屏本身就唔支援第三方輸入法嘅，搜狗乜鬼都唔得。

**Comment by lester1027** [comment]
咁微軟都幾有問題。
唔該。

**Comment by laubonghaudoi** [comment]
@lester1027 建議去 https://github.com/rime/weasel 開個 issue

**Comment by lester1027** [comment]
@laubonghaudoi 其實我已經開左，但得到嘅答案似乎同我嘅情況唔同。
https://github.com/rime/weasel/issues/865
