### ISSUE TITLE
Rime for PC 嘅「中英文语言状态」改为显示「粤」「英」

### ISSUE THREAD

**Issue by isPoto** [rime/rime-cantonese#177]
**Rime 语言状态用「粤」作为「当前粤语中文输入状态」**

我做粤拼小胖项目时嘅想法，当时实现效果如图。：
![image](https://github.com/rime/rime-cantonese/assets/59009389/5253fe27-5633-478f-b8c5-8beb2ba90fe4)

我提供素材：
https://t.me/rime_cantonese/1/145504

点解要用「粤」作为「当前中文输入状态」&「当前粤语输入状态」？

https://t.me/rime_cantonese/1/145473

Poto, [2023/6/1 14:24]
一个「粤」字，有「中文」嘅意思，都有「当前粤语输入状态」嘅意思

Poto, [2023/6/1 14:25]
适用性更广、更符合用户直觉

Poto, [2023/6/1 14:27]
成日话撑粤语，撑粤语係要用细节嚟体现

Poto, [2023/6/1 14:29]
而唔係響度嗌口號

Poto, [2023/6/1 14:32]
边条友噉讲睇到「粤」唔觉得係「当前係中文输入状态」意思嘅？

Poto, [2023/6/1 14:34]
「粤」字本身係中文字，粤拼用户见到「粤」字就知道咩料。

又何必係都要用个「中」字嚟作为「中文输入状态」？

**Comment by laubonghaudoi** [comment]
https://github.com/rime/rime-cantonese/pull/176
