### ISSUE TITLE
问下，我安装了iDvel / rime-ice 如果再安装这个，会不会有冲突

### ISSUE THREAD

**Issue by newyorkthink** [rime/rime-cantonese#179]
我目前安装了iDvel / rime-ice
https://github.com/iDvel/rime-ice
bash rime-install iDvel/rime-ice:others/recipes/full
![image](https://github.com/rime/rime-cantonese/assets/87791643/e774b0dc-c5f7-4229-a8a0-ed1def89b906)

要怎么继续安装[rime-cantonese](https://github.com/rime/rime-cantonese)
两个之间要怎么切换

**Comment by laubonghaudoi** [comment]
呢度係 rime-cantonese唔係rime，安裝相關問題唔該去 [rime](https://github.com/rime) 問
