### ISSUE TITLE
Rime does not work in Minecraft

### ISSUE THREAD

**Issue by IanDaBest** [rime/rime-cantonese#180]
In the text chat in Minecraft, the input does not work and instead uses either Pinyin or English.

**Comment by laubonghaudoi** [comment]
呢個問題應該提喺 https://github.com/rime/home/issues

**Comment by graphemecluster** [comment]
@laubonghaudoi 我覺得噉樣好冇禮貌
你有冇權限 transfer issue？

**Comment by laubonghaudoi** [comment]
冇，如果有我早就transfer咗啦，所以先直接close

**Comment by graphemecluster** [comment]
@laubonghaudoi 可以喺 RIME 羣問下
