### ISSUE TITLE
Error loading table for dictionary 'loengfan'

### ISSUE THREAD

**Issue by juneszh** [rime/rime-cantonese#184]
系統：Windows 11 23H2 22631.3007
安裝方法：[小狼毫 Nightly Build](https://github.com/rime/weasel/releases/tag/latest) + [Windows 進階安裝教程 (視覺界面)](https://github.com/rime/rime-cantonese/wiki/Windows-%E9%80%B2%E9%9A%8E%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B-(%E8%A6%96%E8%A6%BA%E7%95%8C%E9%9D%A2))
問題：最近發現經常使用一段時間後無法輸入中文，需要重啓算法服務才能恢復，睇返`Temp\rime.weasel.xxx.ERROR.xxx.log`：

> Log file created at: 2024/02/08 14:14:24
Running on machine: xxx
Running duration (h:mm:ss): 0:00:00
Log line format: [IWEF]yyyymmdd hh:mm:ss.uuuuuu threadid file:line] msg
E20240208 14:14:24.102775 15500 mapped_file.cc:78] attempt to open non-existent file 'C:\Users\xxx\AppData\Roaming\Rime\build\loengfan.table.bin'.
E20240208 14:14:24.118424 15500 table.cc:260] Error opening table file 'C:\Users\xxx\AppData\Roaming\Rime\build\loengfan.table.bin'.
E20240208 14:14:24.118424 15500 dictionary.cc:332] Error loading table for dictionary 'loengfan'.

疑似同`反查`之中嘅`粵語兩分`有關？查返`C:\Users\xxx\AppData\Roaming\Rime\build`好似係冇相關文件
![图片](https://github.com/rime/rime-cantonese/assets/2436252/33e79575-ca8c-49d1-9b3d-d0372509666f)

請問有什麼解決辦法？

**Comment by ayaka14732** [comment]
要安裝粵語兩分：https://github.com/CanCLID/rime-loengfan
