### ISSUE TITLE
 我想自定义或者拓展，怎么加入到jyut6ping3 输入方案里？？

### ISSUE THREAD

**Issue by Taamyuk** [rime/rime-cantonese#187]
### 
譬如我要加 名字 李红飞  leihungfei 作为一个词语，怎么添加的？直接添加在<jyut6ping3.phrase.dict.yaml>中吗，然后粤拼方案的<jyut6ping3.dict.yaml>文件里面引用了会自动索引的吗？
我没有看到jyut3ping6文件里面有引用 .dict.yaml文件。是默认引用<jyut6ping3.dict.yaml>文件的吗？

**Comment by laubonghaudoi** [comment]
你睇個 https://github.com/rime/rime-cantonese/blob/main/jyut6ping3.dict.yaml 文件，直接喺入面加詞條就得

**Comment by graphemecluster** [comment]
正確，jyut3ping6.schema.yaml 會自動引用 jyut3ping6.dict.yaml。可見 jyut3ping6.dict.yaml 又引用５個文件，因此加入詞條至任何一個 jyut3ping6.*.dict.yaml 文件即可。直接加到 jyut3ping6.dict.yaml 亦可。
