### ISSUE TITLE
 jyut6ping3 issues under iOS and minor under MacOS

### ISSUE THREAD

**Issue by kwccoin** [rime/rime-cantonese#195]
### 問題描述

Follow the instruction with a newly created default.custom.yaml ... (follow instruction)
See a keyboard with the space bar with the title "jyut6ping3" but nothing happen
Input all in English
Back to the iRime iOS App, I note that under the "choose schema", there is no schema 

### 修改意見

For the advance user like using install under iOS, I suggest to say that one has to download the "plum" under macOS advance option and perhaps clearer by stating the need to use the upload instruction.

To solve the above issue of nothing seems to happen, I instead of using "just the few line as a newly created default scheme", I use the full default schema list example.  Then if you choose schema, many options come up.  

(Not sure as I changed the output to traditional chinese and space bar now is not "jyut6ping3" but "粵拼“ but at least it works.)  I said "at least it works" because it seems in the scheme choice you have only "粵拼“ but not 2 options i.e. with an extra "粵拼拼音“ option .  But at least all the input methods appear , with at least one choice of "粵拼“ available there.

Files note: on top of the default yaml, I note your example has user.db and its backup but not mine.  Also the MacOS  have extra files.  I cannot create the user.db but I tried both only 4 files as suggested in your instruction or upload also the additional files come with Rime macOS under the "plum" download.  It seems no effect.

Issues sort of solved except for the missing option of "粵拼拼音“ .

--- further comments:

1. Unlike the default jyuping (of iOS), it does not tell you what is the tone of the work one choose as well.  Hence not sure that is an improvement to use Rime from a learner point of view.  Or I miss something due to the missing option of "粵拼拼音“.

2. Also, I paid for the "Pro" but what is it that for I am not sure. 

3. BTW, the macOS has a minor issue.  To choose option "10" you have to use number 0.  Might as well say 0 instead of 10 down there to avoid confusion.

4.  Also this google drive does not exist: https://drive.google.com/drive/folders/17OvJAkmvR_5oRQzZo_RrDx7t4Xg-hidd

**Comment by kwccoin** [comment]
Sorry what are you talking about.

I thought these two cantoboard定係粵拼輸入法 coming from Google and Apple are totally separated from this Rime Input method as under this method.  Why quoting these two whilst we are talking about Rime!

To answer your question directly I use https://github.com/rime/rime-cantonese/wiki/iOS-安裝教程 here, which also require I run the installation script of https://github.com/rime/rime-cantonese/wiki/macOS-進階安裝教程 to get the plum.

For the advance installation of Rime onto iOS, I can do it with lots of issue as stated above and no advantage so far to these two big one.

**Comment by laubonghaudoi** [comment]
嗰個iRime嘅安裝已經過時，如果你想喺iOS上面用嘅話就用下面其中一個：

- https://apps.apple.com/us/app/cantoboard/id1556817074
- https://apps.apple.com/us/app/jyutping-cantonese-keyboard/id1509367629
- https://apps.apple.com/hk/app/typeduck/id6451192641

喺 macOS上面安裝就直接裝呢個 https://github.com/TypeDuck-HK/TypeDuck-Mac/releases

**Comment by graphemecluster** [comment]
@laubonghaudoi 我喺「iOS 安裝教程」嗰版加咗個 caution 喺頂，話教程已經過時，叫啲人裝呢幾個 app
你得閒 check 一次所有 wiki 頁面睇下有咩嘢要改
