### ISSUE TITLE
请问zip怎么安装啊？

### ISSUE THREAD

**Issue by abc3127552** [rime/rime-cantonese#24]

**Comment by sgalal** [comment]
什麼平台？

**Comment by abc3127552** [comment]
Win10哈------------------ 原始邮件 ------------------
发件人: "sgalal"<notifications@github.com>
发送时间: 2020年3月21日(星期六) 晚上11:54
收件人: "rime/rime-cantonese"<rime-cantonese@noreply.github.com>;
抄送: "LeonDawn"<690820623@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rime/rime-cantonese] 请问zip怎么安装啊？ (#24)




 
什麼平台？
 
&mdash;

**Comment by laubonghaudoi** [comment]
@abc3127552 安裝教程睇呢度 https://hanhngiox.net/install/selection.html

教程入邊有一部分內容已經過時，取決於你用嘅係咩平臺。如果你係用複製 yaml 文件嘅方式嚟裝嘅話，噉直接參考教程入邊嘅操作，將教程入邊用嘅 yaml 文件換成本倉庫嘅幾個 yaml 文件就得。

如果你用嘅係 windows 平臺嘅小狼毫輸入法，噉直接喺個輸入法設定界面打開命令行，然後輸入 `cantonese` 回車就可以一鍵安裝。
