### ISSUE TITLE
發現有遺漏粵拼去邊到報告？

### ISSUE THREAD

**Issue by jmyz0455** [rime/rime-cantonese#27]
今日想讚人『磢镜』，即係靚咁解，不過打咗好耐『saang2 geng3』都打唔出，衹好用『㨘鏡』代替。

查咗下，『磢』有 coeng2、cong2、saang2 三個讀音，只可惜 rime-cantonese 緊收錄『cong2』哩個拼法。咁請問哩種情況點報告好？（要唔要報告好）🧐

**Comment by leimaau** [comment]
@jmyz0455 「磢」字《廣韻》係三等初母字，莊三化二，所以 cong2 係正音，來源 unihan 嘅 saang2 可能係借義訓讀，所以推薦打「省鏡/㨘鏡」就得嘞。

**Comment by laubonghaudoi** [comment]
@leimaau 按照廣韻上面寫初兩切，係唔係應該加埋 coeng2 嘅音？

@jmyz0455 以後有問題直接喺度開 issue就得，亦都歡迎你幫手同啲字音執錯。畢竟兩萬幾隻字十幾萬個詞條我哋人手唔夠。

**Comment by leimaau** [comment]
@laubonghaudoi 大多方言宕開三陽韻的莊組字和知章組字是區分的，例如「裝牀」和「將常」等等，演變到粵語就是一個-ong，一個-oeng，另外也可以看下同小韻的「愴」字讀 -ong，也可以推理得到一樣的結果。

**Comment by laubonghaudoi** [comment]
@leimaau 經過工作組尋晚嘅討論，我哋認爲作爲輸入法碼表係應該喺收音上面寬鬆啲嘅，噉樣可以提高用戶嘅輸入效率，所以我打算將saang2 coeng2都收埋入去

@jmyz0455 呢個issue已經關閉咗，如果仲有問題嘅話可以重新開返繼續討論。

**Comment by leimaau** [comment]
@laubonghaudoi 隨便你哋，但所謂 磢鏡 嘅寫法完全錯誤，穿鑿附會，啲字唔係越複雜越啱，越複雜越可能係亂嚟嘅。

**Comment by jmyz0455** [comment]
> 所謂 磢鏡 嘅寫法完全錯誤，穿鑿附會，啲字唔係越複雜越啱，越複雜越可能係亂嚟嘅。

@leimaau  我生活中、電視中無聽過 cong2 哩個音，可能逐漸有啲失傳，但如果 cong2 先至係正音，咁用標準嘅音就最好。事關我嘅粵拼係跟 jyput 輸入法學嘅，我希望打嘅每日隻字都係正音，唔好貪方便，如果唔係爲咗學粵拼，我都唔會用 jyput 輸入法。反而用『㨘鏡』就幾好，廣東人就睇得明。

@laubonghaudoi 多謝曬你哋。

**Comment by leimaau** [comment]
@jmyz0455 唉~我都有啲反思我自己係咪唔夠包容😂

**Comment by leimaau** [comment]
@jmyz0455 我同 @laubonghaudoi 嘅關係好好嘅，正因爲我哋相熟，我先有噉嘅語氣同佢講話，過於傲嬌，唔好誤會啊😂 我都反思我自己係咪有啲唔夠包容。
