### ISSUE TITLE
修復「台」字

### ISSUE THREAD

**Issue by sgalal** [rime/rime-cantonese#29]
在 #19 中本應將異體字全部修正爲 OpenCC 標準，但因「台」字的對應關係較為複雜，暫時沒有修復。

目前碼表中有三百餘個「台」字，應該需要人工修正。

參考：<https://github.com/BYVoid/OpenCC/blob/master/data/scheme/st_multi.txt>

> 與「平地」有關用「臺」，與「櫃檯」有關用「檯」，與「颱風」有關用「颱」。「台」爲罕用字。	看臺 高臺 電視臺 寫字檯 颱風 兄台 天台山 五臺山 臺灣

**Comment by laubonghaudoi** [comment]
發台瘟
豐台
豐台區
鳳台
鳳台縣
東台
東台市
九台
九台市
蓋台廣告
港台
高台縣
國務院台灣事務辦公室
一中一台
煙台
煙台地區
煙台市
邢台
邢台地區
邢台縣	
邢台市	
瑤台
魚台
魚台縣
禹王台	jyu5 wong4 toi4	
禹王台區	jyu5 wong4 toi4 keoi1	
奇台	kei4 toi4	
奇台縣	kei4 toi4 jyun6	
輪台	leon4 toi4	
輪台古城	leon4 toi4 gu2 sing4	
輪台縣	leon4 toi4 jyun6	
靈台	ling4 toi4	
靈台縣	ling4 toi4 jyun6	
梁山伯與祝英台	loeng4 saan1 baak3 jyu5 zuk1 jing1 toi4	
茅台	maau4 toi4	
霧台	mou6 toi4	
霧台鄉	mou6 toi4 hoeng1	
帕台農	paak3 toi4 nung4	
帕台農神廟	paak3 toi4 nung4 san4 miu2	
蒲台島	pou4 toi4 dou2	
三台	saam1 toi4	
三台縣	saam1 toi4 jyun6	
新台幣	san1 toi4 bai6	
神台	san4 toi2	
神檯	san4 toi2	
神台桔	san4 toi2 gat1	
神檯桔	san4 toi2 gat1	
神台貓屎	san4 toi2 maau1 si2	
神台桔	san4 toi4 gat1	
神台貓屎	san4 toi4 maau1 si2	
四仔台	sei3 zai2 toi4	
斯台普斯	si1 toi4 pou2 si1	
仙台	sin1 toi4	
蘇台德地區	sou1 toi4 dak1 dei6 keoi1	
叔台	suk1 toi4	
宋王台	sung3 wong4 toi4
