### ISSUE TITLE
因爲 -> 因為

### ISSUE THREAD

**Issue by tyteen4a03** [rime/rime-cantonese#31]
呢個為字喺不轉換之下會變咗做爲，我要自己晌dict上面自己加返為字。唔知有冇方法解決？

**Comment by laubonghaudoi** [comment]
呢個「爲」字，係我哋專登設嘅，因爲呢個字先係傳統嘅正寫法，亦都係opencc標準入邊嘅默認用字。「為」係後起嘅俗字，而我哋嘅碼表入邊所有詞條都默認採用opencc標準字形組詞，所以詞條入邊唔會有呢隻字。你如果想打「為」，可以直接撳<kbd>Ctrl</kbd>+<kbd>`</kbd>然後撳2，然後可以見到也得揀唔同地區嘅字形。默認係揀「不轉換」即係opencc字形，你揀香港繁體就得
![image](https://user-images.githubusercontent.com/11172180/79396693-538b8900-7f31-11ea-8e0e-961b28af83ec.png)

**Comment by laubonghaudoi** [comment]
啱先嘅更新 https://github.com/rime/rime-cantonese/commit/671db60550a168ed8d15a995de3de0ca1a46781d 改咗個字體名，而家揀「香港傳統漢字」就得
