### ISSUE TITLE
請問能否支援中英文混合打字

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#32]
在家辦公有時要打英文詞彙，但輸入法方案係冇嘅。
譬如：『suppor』，候選項目就優先顯示英文詞彙support。

**Comment by sgalal** [comment]
有可能，我得閒研究下

**Comment by laubonghaudoi** [comment]
目前中英混合輸只能夠靠喺碼表入邊增加詞條嘅方法嚟實現，亦即係`jyut6ping3.lettered.dict.yaml`入邊嘅數據。呢種解決方案算係最原始簡單嘅方法，因爲rime係個開源軟件，唔似google呢啲大公司有英文詞庫或者中英混合語言模型之類嘅工具，所以只能夠噉樣做。你講嘅嗰種效果，應該係指輸入任何英文單詞？呢個基本上冇可能實現。因爲按照而家嘅解決方案，相當於將成部英語字典都抄落去個yaml文件度，當然如果你得閒嘅話可以自己試下，只不過我估個輸入法都會變卡。

**Comment by sgalal** [comment]
![用粵拼輸入法輸入英文單詞的畫面](https://user-images.githubusercontent.com/32255369/79531224-493dcc00-80a4-11ea-8056-509e46998e93.png)

[rime-easy-en](https://github.com/BlindingDark/rime-easy-en) 用 `abc_segmentor` 嘅 `extra_tags` 好似可以，我試咗下，但係一次只能打中文/打英文，冇辦法混打。仲需要繼續研究下。

**Comment by tiujejauci** [comment]
> ![用粵拼輸入法輸入英文單詞的畫面](https://user-images.githubusercontent.com/32255369/79531224-493dcc00-80a4-11ea-8056-509e46998e93.png)
> 
> [rime-easy-en](https://github.com/BlindingDark/rime-easy-en) 用 `abc_segmentor` 嘅 `extra_tags` 好似可以，我試咗下，但係一次只能打中文/打英文，冇辦法混打。仲需要繼續研究下。

係啦，我要嘅就係想噉樣，唔想突然打英文要轉輸入法咁麻煩，之前喺百度貼吧見到呢個post： https://tieba.baidu.com/p/4085621846 ，不過係舊版。

**Comment by sgalal** [comment]
@tiujejauci 打英文唔需要切換輸入法，撳 <kbd>Shift</kbd> 切換中英文就得呀

**Comment by tiujejauci** [comment]
> @tiujejauci 打英文唔需要切換輸入法，撳 Shift 切換中英文就得呀

我英文比較屎 想借助下輸入候選項 提醒自己有冇出錯字嗟

**Comment by laubonghaudoi** [comment]
但係 rime-easy-en 本質上都係將啲英文單詞當成一個詞條，如果想實現中英混打仲係要將啲各種詞組組合寫落個碼表度，噉樣唔現實。唔知 rime 有冇中英混合語言模型嘅功能，不過呢個都唔係碼表層面嘅嘢嘞。

**Comment by tiujejauci** [comment]
> 但係 rime-easy-en 本質上都係將啲英文單詞當成一個詞條，如果想實現中英混打仲係要將啲各種詞組組合寫落個碼表度，噉樣唔現實。唔知 rime 有冇中英混合語言模型嘅功能，不過呢個都唔係碼表層面嘅嘢嘞。

https://github.com/BlindingDark/rime-easy-en

「
如果想要中英混输效果，以朙月拼音（luna_pinyin）为例，可执行以下命令：

bash rime-install BlindingDark/rime-easy-en:customize:schema=luna_pinyin
」（未試過）

**Comment by laubonghaudoi** [comment]
> > 但係 rime-easy-en 本質上都係將啲英文單詞當成一個詞條，如果想實現中英混打仲係要將啲各種詞組組合寫落個碼表度，噉樣唔現實。唔知 rime 有冇中英混合語言模型嘅功能，不過呢個都唔係碼表層面嘅嘢嘞。
> 
> https://github.com/BlindingDark/rime-easy-en
> 
> 「
> 如果想要中英混输效果，以朙月拼音（luna_pinyin）为例，可执行以下命令：
> 
> bash rime-install BlindingDark/rime-easy-en:customize:schema=luna_pinyin
> 」（未試過）

嗰個 rime-easy-en 只不過係將英文詞條碼表掛載到原有個碼表入邊，同個 emoji 輸入係一樣嘅。我唔知你究竟係想用真正嘅中英混打，即係打【ngojiusupport】 出【我要support】，定係單純提示英文單詞，即係打【suppor】出【support 】？ 如果係前者，噉就係我之前講嘅要有中英混合語言模型先得，rime冇得實現。如果係後者，噉就係你講嘅直接掛載個 rime-easy-en 就得。

**Comment by sgalal** [comment]
@tiujejauci 如果係後者，我測試咗應該冇問題了。可以打 `bash rime-install BlindingDark/rime-easy-en:customize:schema=jyut6ping3` 自動配置；或者安裝 rime-easy-en 之後，參考 <https://github.com/BlindingDark/rime-easy-en/blob/master/easy_en.yaml> 手動修改方案：

`/schema/dependencies` 下第一項加入 `easy_en`

`/engine/translators/script_translator` 後加一項 `table_translator@easy_en`

喺文件末尾加入：

```yaml
easy_en:
  __include: easy_en.schema:/translator

abc_segmentor:
  extra_tags:
    - easy_en  # 同英文混打
```

**Comment by tiujejauci** [comment]
> @tiujejauci 如果係後者，我測試咗應該冇問題了。可以打 `bash rime-install BlindingDark/rime-easy-en:customize:schema=jyut6ping3` 自動配置；或者安裝 rime-easy-en 之後，參考 https://github.com/BlindingDark/rime-easy-en/blob/master/easy_en.yaml 手動修改方案：
> 
> `/schema/dependencies` 下第一項加入 `easy_en`
> 
> `/engine/translators/script_translator` 後加一項 `table_translator@easy_en`
> 
> 喺文件末尾加入：
> 
> ```yaml
> easy_en:
>   __include: easy_en.schema:/translator
> 
> abc_segmentor:
>   extra_tags:
>     - easy_en  # 同英文混打
> ```

前者windows7解決失敗：
https://drive.google.com/file/d/1AEwvhrL1kXjfDXNpZv48fOVbloFAhTo1/view

**Comment by laubonghaudoi** [comment]
@kunki 睇個樣似係冇擒牆，唔係程序原因

**Comment by tiujejauci** [comment]
> @kunki 睇個樣似係冇擒牆，唔係程序原因

系統級別嘅嘢 唔係好識整。。。

**Comment by tiujejauci** [comment]
> @kunki 睇個樣似係冇擒牆，唔係程序原因

試過，擒咗都係404 not foundhttps://drive.google.com/file/d/1KI9sScOpFgkT2tsXK7xiWgdgPgTnhQuT/view

**Comment by tiujejauci** [comment]
> @tiujejauci 如果係後者，我測試咗應該冇問題了。可以打 `bash rime-install BlindingDark/rime-easy-en:customize:schema=jyut6ping3` 自動配置；或者安裝 rime-easy-en 之後，參考 https://github.com/BlindingDark/rime-easy-en/blob/master/easy_en.yaml 手動修改方案：
> 
> `/schema/dependencies` 下第一項加入 `easy_en`
> 
> `/engine/translators/script_translator` 後加一項 `table_translator@easy_en`
> 
> 喺文件末尾加入：
> 
> ```yaml
> easy_en:
>   __include: easy_en.schema:/translator
> 
> abc_segmentor:
>   extra_tags:
>     - easy_en  # 同英文混打
> ```

還有就係 後者 係點樣加？jyut6ping3.schema.yaml？

**Comment by laubonghaudoi** [comment]
即係話你用同樣嘅方法加emoji冇問題，加easy-en就唔得？呢兩者係等價嘅，如果你加emoji得冇理由easy-en唔得

**Comment by tiujejauci** [comment]
> 即係話你用同樣嘅方法加emoji冇問題，加easy-en就唔得？呢兩者係等價嘅，如果你加emoji得冇理由easy-en唔得

唔係呀，打 rime-easy-en係得嘅，
但係打rime-install BlindingDark/rime-easy-en:customize:schema=jyut6ping3

**Comment by laubonghaudoi** [comment]
噉你運行`bash rime-install emoji:customize:schema=luna_pinyin`得唔得？

**Comment by tiujejauci** [comment]
> 噉你運行`bash rime-install emoji:customize:schema=luna_pinyin`得唔得？

![image](https://user-images.githubusercontent.com/31369434/79825152-d0ec4900-83ca-11ea-9482-9303c4783004.png)
都係唔得。。

**Comment by tiujejauci** [comment]
我係噉樣開嘅，首先開啓小狼毫輸入法「設定」
![image](https://user-images.githubusercontent.com/31369434/79825225-0e50d680-83cb-11ea-82b6-6998f63b1626.png)

然後撳「獲取更多輸入方案」
然後就噉樣...

**Comment by laubonghaudoi** [comment]
@tiujejauci 噉就更加說明唔係個方案問題，係你個網絡問題嘞。噉你只能夠用手動方式添加掛載個 easy-en 或者 emoji，冇得用命令行。

你先按照 https://github.com/rime/rime-emoji 入邊講嘅「自助安裝」嚟裝 emoji，睇下得唔得，然後再按照相同嘅方式嚟裝個 easy-en

**Comment by tanxpyox** [comment]
> > 噉你運行`bash rime-install emoji:customize:schema=luna_pinyin`得唔得？
> 
> ![image](https://user-images.githubusercontent.com/31369434/79825152-d0ec4900-83ca-11ea-9482-9303c4783004.png)
> 都係唔得。。

試下安裝Git for Windows然後試多次。因爲系統預設如果你冇安裝git嘅話，佢只會用wget嚟下載輸入法。

**Comment by laubonghaudoi** [comment]
原來係冇裝git，噉一唔係就裝個git，一唔係就按照上面講嘅手動配置

**Comment by tiujejauci** [comment]
> > > 噉你運行`bash rime-install emoji:customize:schema=luna_pinyin`得唔得？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/31369434/79825152-d0ec4900-83ca-11ea-9482-9303c4783004.png)
> > 都係唔得。。
> 
> 試下安裝Git for Windows然後試多次（唔使輸入`rime-install`)。因爲系統預設如果你冇安裝git嘅話，佢只會用wget嚟下載輸入法。（記得啓用Git Bash)
> ![image](https://user-images.githubusercontent.com/9696140/80176768-3a1ec700-862c-11ea-90e8-374cd89d8f8e.png)
> ^正確示範

我已經裝左git了
![image](https://user-images.githubusercontent.com/31369434/80270904-99451000-86ee-11ea-9fae-1e5b8744a0eb.png)

**Comment by laubonghaudoi** [comment]
噉你用手動方法安裝得唔得？

**Comment by tiujejauci** [comment]
> 噉你用手動方法安裝得唔得？

手動下載rime-Cantonese倉庫，然後解壓縮，拖入rime用戶資料夾，重新部署，就OK

**Comment by laubonghaudoi** [comment]
係，我意思係話，你係一直想將個easy-en掛載到個rime-cantonese𠺢嘛，係唔係？噉而家要用手動方式來掛載，有冇成功？

**Comment by tiujejauci** [comment]
> 係，我意思係話，你係一直想將個easy-en掛載到個rime-cantonese𠺢嘛，係唔係？噉而家要用手動方式來掛載，有冇成功？

冇哇
不過我係睇 百度rime貼吧講解
新建jyut6ping3.custom.yaml

patch:
  # 加載 easy_en 依賴
  "schema/dependencies/@next": easy_en
  # 載入翻譯英文的碼表翻譯器，取名爲 english
  "engine/translators/@next": table_translator@english
  # english 翻譯器的設定項
  english:
    dictionary: easy_en
    spelling_hints: 9
    enable_completion: true
    enable_sentence: false
    initial_quality: -1
