### ISSUE TITLE
編譯錯誤

### ISSUE THREAD

**Issue by tanxpyox** [rime/rime-cantonese#39]
哩啲字詞部署唔到入去個輸入法度，應該係因爲啲字詞喺*.phrase.dict入面出現咗，但係搵唔到碼表嘅相應拼音。

因爲個list長得滯，所以我將佢paste咗[響度](https://pastebin.com/nsbc6M4P)，方便大家睇。

**Comment by laubonghaudoi** [comment]
可唔可以畀多啲信息？係編譯乜嘢？如果係使用呢個碼表打字嘅話，直接粘貼重新部署就得

**Comment by tanxpyox** [comment]
好似「白雲邨」咁，係jyut6ping3.phrase.dict.yaml入面有收錄，但係打唔出。我估計係因爲冇喺.dict入面定義 `邨  cyun1` 所致。

我用緊Windows，部署落jyut6ping3度。(我係用最新嗰嗰commit嚟編譯嘅）

**Comment by tanxpyox** [comment]
```
	cyu5	
䆤	cyun1	
䆥	cyun1	
川	cyun1	
村	cyun1	
氚	cyun1	
汆	cyun1	
穿	cyun1	
踆	cyun1	
躥	cyun1	
釧	cyun1	
鋑	cyun1	
鑹	cyun1	
䞼	cyun2
```
如果冇收「邨」字，咁嗰啲係*.phrase*入面有個「邨」字(但係冇係.dict度定義）嘅詞就會全部打唔出。

**Comment by tanxpyox** [comment]
我諗可以用將個list放入電腦程式入面計算每粒字喺個list出現嘅頻率，最高頻率嗰啲應該就係漏咗收錄嘅字嘞。

**Comment by laubonghaudoi** [comment]
嗰個.phrase.dict文件入邊有好多錯我哋仲未改過來.至於收字問題，我哋都喺度考慮緊點樣修復。歡迎直接PR補丁

**Comment by tanxpyox** [comment]
我想問下如果.phrase.dict入面有異體字，係應該將.phrase.dict改番正字，定係喺.dict度加埋異體字讀音？

**Comment by laubonghaudoi** [comment]
所有詞條均默認採用 opencc 字體

**Comment by tanxpyox** [comment]
字 | 音 | 註 
-- | -- | -- 
栢 | baak3 |  | 
埗 | bou3 | |
鉢 | but3 | |
産 | caan2 | 好似係日本新字體，但係phrase度有收|
槙 | can2 | 異讀 zan2|
鷄 | gai1 | 應該係異體|
箂 | loi4 | |
郞| long4 | 郎嘅異體, phrase 有收 |
竉 | lung1 | 搵唔到讀音，但係phrase度當「窿」字噉用 |
綫 | sin3 | 異體但係廣泛使用 |
蟮 | sin6 | |
坣 | tong4 | 二簡字，建議改phrase，此風不可長 |
滙 | wui6 | 匯嘅異體？廣泛使用|
眞 | zan1 |
嗻 | ze1 | 搵唔到音，但phrase當「啫」噉用|

收住噉多先，得閒再睇。

**Comment by tanxpyox** [comment]
差個「竓」字，其他喺我個PR 度解決埋嘞。

```
E0422 23:38:12.378471  7472 entry_collector.cc:133] Encode failure: '上竓'.
E0422 23:38:12.604684  7472 entry_collector.cc:133] Encode failure: '食🍚'.
E0422 23:38:13.022141  7472 entry_collector.cc:133] Encode failure: '瓦竓頭'.
E0422 23:38:13.456939  7472 entry_collector.cc:133] Encode failure: '湘屯阝'.
E0422 23:38:14.179159  7472 entry_collector.cc:133] Encode failure: '有👀睇'.
E0422 23:38:14.722486  7472 entry_collector.cc:133] Encode failure: '磚竓'.
```

**Comment by leimaau** [comment]
嗰個「竓」嘅「上竓、瓦竓頭、磚竓」係咩嚟嘅，正確嘅字搵唔到。

**Comment by tanxpyox** [comment]
我都唔知，不如刪除。

**Comment by tanxpyox** [comment]
4b374457569ad1f42fd28a677a9aee3160ef08f9 完成修復

**Comment by laubonghaudoi** [comment]
嗰個應該係「毫」字嘅異體字

**Comment by sgalal** [comment]
「坣」字唔一定係錯誤，比如搜索「致坣工業園」就揾到，但係改成「堂」、「壆」都揾唔到。

地圖亦都係「坣」，所以可能係地名用字：

![谷歌地圖搜索「致坣工業園」的結果](https://user-images.githubusercontent.com/32255369/80025879-d903d000-8513-11ea-9868-59f22685fab9.png)

**Comment by laubonghaudoi** [comment]
> 「坣」字唔一定係錯誤，比如搜索「致坣工業園」就揾到，但係改成「堂」、「壆」都揾唔到。
> 
> 地圖亦都係「坣」，所以可能係地名用字：
> 
> ![谷歌地圖搜索「致坣工業園」的結果](https://user-images.githubusercontent.com/32255369/80025879-d903d000-8513-11ea-9868-59f22685fab9.png)

如果係噉，我哋要將個「坣」改過來？

**Comment by leimaau** [comment]
應該係深圳嘅哋名， 我喺地圖搜索「壆崗」一類嘅詞就可以搵到，網上見有唔少關於「坣、壆」嘅討論。

**Comment by sgalal** [comment]
按照 <http://baoliao.oeeee.com/67572.html> 這個 (網頁 / [Archive Page](https://web.archive.org/web/20200423071942/http://baoliao.oeeee.com/67572.html)) 中的説法，當地人確實使用「坣」字，讀音 bo 應該對應 bok3。

**Comment by sgalal** [comment]
> 嗰個「竓」嘅「上竓、瓦竓頭、磚竓」係咩嚟嘅，正確嘅字搵唔到。

應該係「窰」。「上窰、瓦窰頭、磚窰」都係香港地名，讀 <span lang="yue-Latn-HK">jiu4</span>。
