### ISSUE TITLE
phrase.dict 內的「甘」字

### ISSUE THREAD

**Issue by szc126** [rime/rime-cantonese#40]
`甘又是` `甘好玩` `甘都有`等等，應該是錯誤吧。

**Comment by laubonghaudoi** [comment]
phrase.dict 入邊嘅詞條大部分冇經過校對，請問仲有咩問題？我一次過修埋

**Comment by laubonghaudoi** [comment]
https://github.com/rime/rime-cantonese/commit/0070fe418d5c266c79af02952d1dd0f7be5add3a

**Comment by szc126** [comment]
唔知道仲有冇，我只係偶然發現咗呢一個。

**Comment by laubonghaudoi** [comment]
我啱新建咗個 issue 模板，以後按照嗰個模板來反饋詞條單字問題，最好一次過收齊再統一反饋，噉樣可以提高效率
