### ISSUE TITLE
我今日裝咗rime-cantonese/releases嘅windows版本粵拼

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#49]
我今日裝咗[rime-cantonese/releases嘅windows版本粵拼](https://github.com/rime/rime-cantonese/releases)，
發現內建嘅粵拼係rime-jyutping方案，唔係rime-cantonese方案，打字有細微嘅出入。

想問下點樣可以做到自動更新？

又手動拉zip解壓再覆蓋？

**Comment by laubonghaudoi** [comment]
我哋檢查過打包嘅係 rime-cantonese 方案，可唔可以截圖睇下你嘅係咩情況？方案名叫咩？石打得出聲調？

## Windows 版更新碼表步驟

### 第一步：從開始菜單中打開「小狼毫輸入法設定」

![image](https://user-images.githubusercontent.com/11172180/80624085-08c54300-8a00-11ea-8f7d-04728b634de2.png)

### 第二步：揀「獲取更多輸入方案」

![image](https://user-images.githubusercontent.com/11172180/80624353-69ed1680-8a00-11ea-8307-0013be2e3db1.png)


### 第三步：輸入`cantonese`，回車，開始更新碼表：

![image](https://user-images.githubusercontent.com/11172180/80624325-5b066400-8a00-11ea-9de2-6b8acb766083.png)

### 第四步：關閉命令行窗口，撳「中」關閉設定窗口，重新部署，即更新完成。

**Comment by tiujejauci** [comment]
修改系統默認出香港正體字（以windows7為例）：
1、撳 開始菜單 → （呢個符號「→」係複製嘅 其實我都唔知點打出嚟）所有程式→小狼毫輸入法 →【小狼毫】用戶文件夾
![1](https://user-images.githubusercontent.com/31369434/80818330-8e661000-8c05-11ea-9da7-cc8e0a344a0c.png)
2、用notepad++開啟jyut6ping3.schema.yaml
![2](https://user-images.githubusercontent.com/31369434/80818451-c79e8000-8c05-11ea-82cb-4d5756e98959.PNG)
3、拉到下邊 switches: 部分,
見到- options: [ noop, trad_hk, trad_tw, simplification ],新增reset: 1，如圖所示：
![3](https://user-images.githubusercontent.com/31369434/80818500-ddac4080-8c05-11ea-9bdc-0abd731ec20e.png)
4、儲存
5、撳 開始菜單 → 所有程式→小狼毫輸入法 →【小狼毫】重新部署

**Comment by tiujejauci** [comment]
改字型+改字型大細+DIY主題（以windows7為例）：

1、撳 開始菜單 → 所有程式 → 小狼毫輸入法 →【小狼毫】用戶文件夾
2、用notepad++開啟weasel.custom.yaml
3、如圖
patch:
  "style/color_scheme": SauGau （改主題）
  "style/font_face": "微軟正黑體" （改字型）
  "style/font_point": 14 （改字型大細）
  "preset_color_schemes/SauGau": （改主題）
    name: SauGau/搜狗 （主題名，具體請入[呢度](https://github.com/rime/home/wiki/CustomizationGuide#%E4%B8%80%E4%BE%8B%E5%AE%9A%E8%A3%BD%E5%B0%8F%E7%8B%BC%E6%AF%AB%E9%85%8D%E8%89%B2%E6%96%B9%E6%A1%88)）
    author: 作者
    back_color: 0xFFFFFF
    border_color: 0xFFFFFF
    text_color: 0xB96205
    hilited_text_color: 0xB96205
    hilited_back_color: 0xFFFFFF
    hilited_candidate_text_color: 0x0000FF
    hilited_candidate_back_color: 0xFFFFFF
    candidate_text_color: 0xE58200
    comment_text_color: 0xB96205
![image](https://user-images.githubusercontent.com/31369434/80819494-a9398400-8c07-11ea-86b4-8276f11ab5d0.png)

**Comment by laubonghaudoi** [comment]
所以你嘅問題已經解決咗嘞？我關個issue嘞

**Comment by tiujejauci** [comment]
> 所以你嘅問題已經解決咗嘞？我關個issue嘞

可唔可以將呢個issues執一執 放入常見問題（Q & A）？

**Comment by laubonghaudoi** [comment]
我加咗落 Wiki入邊 https://github.com/rime/rime-cantonese/wiki/Windows-%E6%9B%B4%E6%96%B0%E7%A2%BC%E8%A1%A8%E6%AD%A5%E9%A9%9F

**Comment by tiujejauci** [comment]
Windows10輸入法切換請入[呢度](https://zhuanlan.zhihu.com/p/91129641)（簡化字），當中第4點。

**Comment by tiujejauci** [comment]
### **候選項目改成9個**

1.、撳 開始菜單 → 所有程式 → 小狼毫輸入法 →【小狼毫】用戶文件夾

2、用notepad++開啟default.custom.yaml

3、見到：
patch:
  schema_list:
    - {schema: jyut6ping3}
另起一行，新增
  ### menu/page_size: 9 
如圖
![image](https://user-images.githubusercontent.com/31369434/80854300-8e97f700-8c69-11ea-9f0b-d4329303b02e.png)

**Comment by tiujejauci** [comment]
> ### 第三步：輸入`cantonese`，回車，開始更新碼表：
> ![image](https://user-images.githubusercontent.com/11172180/80624325-5b066400-8a00-11ea-9de2-6b8acb766083.png)
 補充：
 @SirnoChan 提到Win10 1903 的 Windows Terminal支援bash命令，咁其它Windows版本喺裝Rime之前，必須先安裝git for Windows。

https://github.com/rime/rime-emoji/issues/6#issuecomment-562821839

**Comment by tiujejauci** [comment]
自動識別西文及數字組成的用戶名
1.、撳 開始菜單 → 所有程式 → 小狼毫輸入法 →【小狼毫】用戶文件夾

2、用notepad++開啟default.custom.yaml

3、見到：

patch:
  schema_list:
    - {schema: jyut6ping3}
另起一行，新增
  recognizer/patterns/rime123: "^rime[0-9]+$"
  recognizer/patterns/rimeime: "^rimeime[-_.0-9]*$"
如圖
![image](https://user-images.githubusercontent.com/31369434/106161873-720df880-61c2-11eb-9181-e0d461e797b0.png)

4、儲存

5、撳 開始菜單 → 所有程式→小狼毫輸入法 →【小狼毫】重新部署

來源：https://gist.github.com/lotem/3076166

**Comment by tiujejauci** [comment]
剷走 顯示候選項目顯示自己打嘅錯詞：

唔小心打錯詞，再打同樣拼音，錯詞一直喺候選欄，可以：
先用↑或↓掣揀中要剷走項目，
跟住撳 Shift+Delete 或 Control+Delete（蘋果鍵盤用 Shift+Fn+Delete）。

*剷走非自己打錯項目，只會調整詞彙顯示排序。
原文：https://github.com/rime/home/wiki/UserGuide#%E5%88%AA%E9%99%A4%E8%AA%A4%E4%B8%8A%E5%B1%8F%E7%9A%84%E9%8C%AF%E8%A9%9E

**Comment by tiujejauci** [comment]
（唔係粵英夾雜）候選項目新增英文詞彙：
轉寄自百度rime貼吧

1. 打開rime用戶資料夾位置
2. 用記事簿程式 新增jyut6ping3.custom.yaml，添加如下內容：
```
__patch:
patch:
  # 加載 easy_en 依賴
  "schema/dependencies/@next": easy_en
  # 載入翻譯英文的碼表翻譯器，取名爲 english
  "engine/translators/@next": table_translator@english
  # english 翻譯器的設定項
  english:
    dictionary: easy_en
    spelling_hints: 9
    enable_completion: true
    enable_sentence: false
    initial_quality: -1
```
initial_quality一般設為-1，可以試下0-0.5之間之數值，數值越大，英文詞彙越前。

3. 儲存，然後重新部署

**Comment by tiujejauci** [comment]
備份自己詞典：
![image](https://user-images.githubusercontent.com/31369434/122729932-48a65400-d2ac-11eb-9329-0af71ba6c65a.png)
用戶詞典管理→輸出詞典快照

回復自己詞典：
用戶詞典管理→合入詞典快照
