### ISSUE TITLE
Ubuntu 18.04 LTS使用"Ubuntu Pop!_OS 安裝教程"嘅方法安裝嘅問題：粵語打唔出

### ISSUE THREAD

**Issue by YexiongLin** [rime/rime-cantonese#52]
我用嘅系ubuntu 18.04 lts，我發現使用教程嘅方法安裝有兩個問題：

1. 執行完教程嘅步驟之後，撳ctrl + ` ，沒有出現【粵語拼音】。
默認嘅default.custom.yaml好似唔啱，格式要改成
patch:
  schema_list:
    - schema: jyut6ping3 
噉樣先得（選擇菜單只得粵語拼音，其他亦要加入去）

2. 我發現呢，就算出現咗粵語拼音，都打唔出字。我懷疑系安裝版本嘅問題，我用sudo apt-get install ibus-rime 先得。同時我發現用明月拼音打普通話ao變成an，例如我打pao就會出現讀音系pan嘅詞，an變成ai等等。用sudo apt-get install ibus-rime一切搞定。

就係噉，希望改改咯

**Comment by tanxpyox** [comment]
咁奇？本身已經係
![image](https://user-images.githubusercontent.com/9696140/81312246-00809e00-90b9-11ea-98f7-aec8bb52a3d1.png)
嘎啦喎

**Comment by YexiongLin** [comment]
前面格式有問題，補充
`patch:
  schema_list:
  - schema: luna_pinyin
  - schema: cangjie5
  - schema: luna_pinyin_fluency
  - schema: luna_pinyin_simp
  - schema: luna_pinyin_tw
  - schema: jyut6ping3             # 粵拼`

**Comment by tanxpyox** [comment]
請問係唔係全新安裝？可以嘅話希望可以列出製造嗰個bug出嚟嘅步驟

**Comment by YexiongLin** [comment]
> 請問係唔係全新安裝？可以嘅話希望可以列出製造嗰個bug出嚟嘅步驟

就係按照教程來安裝，可能系系統唔一樣

**Comment by tanxpyox** [comment]
> 2\. 用sudo apt-get install ibus-rime一切搞定

尤其呢度，因爲本身個教程都係用`sudo apt-get install ibus-rime` 㗎喎

**Comment by YexiongLin** [comment]
> 請問係唔係全新安裝？可以嘅話希望可以列出製造嗰個bug出嚟嘅步驟

我裝個兩次，大一次系用sudo apt-get install ibus-rime安裝嘅，之後我刪咗佢同埋ibus裏面嘅rime文件夾，再重裝

**Comment by tanxpyox** [comment]
:fearful: 手動刪除？定喺 `sudo apt-get autoremove ibus-rime` ?

**Comment by YexiongLin** [comment]
> fearful 手動刪除？定喺 `sudo apt-get autoremove ibus-rime` ?

sudo apt-get remove ibus-rime再刪rime文件夾

**Comment by tanxpyox** [comment]
你係唔係本身有用開RIME輸入法？
因爲嗰段代碼只喺俾全新安裝嘅人用（亦即係~/.config/ibus/rime無default.custom.yaml嘅人用）

如果本身有用開RIME，而且入面係以`patch:`格式寫成， 噉就同我呢個補丁唔相容嘎啦。

**Comment by YexiongLin** [comment]
> 你係唔係本身有用開RIME輸入法？
> 因爲嗰段代碼只喺俾全新安裝嘅人用（亦即係~/.config/ibus/rime無default.custom.yaml嘅人用）
> 
> 如果本身有用開RIME，而且入面係以`patch:`格式寫成， 噉就同我呢個補丁唔相容嘎啦。

的確用咗，，之前我用嘅系無聲調嘅舊版，後來想換，我首先直接把*.yaml冚唪唥加入rime文件夾，再改default.yaml。之後ubuntu仲報rime嘅錯

**Comment by tanxpyox** [comment]
如來係噉，噉我應該係ubuntu教程度清楚寫明嗰條代碼係新手專用，
如果有用開其他RIME輸入法嘅話就應該用：
```sh
cd ~/plum
bash rime-install cantonese
``` 
噉我close呢個issue啦。
