### ISSUE TITLE
Windows封裝

### ISSUE THREAD

**Issue by tanxpyox** [rime/rime-cantonese#53]
我嘗試fork咗個小狼毫嘅程式碼然後將入面嘅預設檔案改成預設安裝rime-cantonese, emoji 同埋 sgalal/rime-opencc-32bit-latest，跟住將default.yaml改成只得jyut6ping3一個輸入方案。（我本來諗住用submodule嚟實現嘅，但係git clone極都有問題，所以索性fork咗佢，之後手動更新算。）

個exe檔係用Appveyor自動封裝嘅，可以喺Release入面搵到。

得閒可以幫手bug test下。

https://github.com/tanxpyox/weasel/releases

**Comment by laubonghaudoi** [comment]
唔該晒！不過我覺得可以考慮除咗`jyut6ping3`之外再加個朙月拼音同倉頡仲有五筆畫，因爲我哋默認係用呢三個反查嘅，如果剩得一個方案嘅話即係呢啲反查都用唔到。不過如果懶得加嘅話就算數嘞，就噉都冇問題。

**Comment by tanxpyox** [comment]
> 唔該晒！不過我覺得可以考慮除咗`jyut6ping3`之外再加個朙月拼音同倉頡仲有五筆畫，因爲我哋默認係用呢三個反查嘅，如果剩得一個方案嘅話即係呢啲反查都用唔到。不過如果懶得加嘅話就算數嘞，就噉都冇問題。

要喺default.yaml度加埋wubi 同埋倉頡先用到反查？我只喺係原本個程式碼上面加粵拼上去，所以嗰啲咩嘢八股文呀，朙月拼音呀全部都應該包哂。

**Comment by laubonghaudoi** [comment]
> > 唔該晒！不過我覺得可以考慮除咗`jyut6ping3`之外再加個朙月拼音同倉頡仲有五筆畫，因爲我哋默認係用呢三個反查嘅，如果剩得一個方案嘅話即係呢啲反查都用唔到。不過如果懶得加嘅話就算數嘞，就噉都冇問題。
> 
> 要喺default.yaml度加埋wubi 同埋倉頡先用到反查？我只係喺原本個程式碼上面加粵拼上去，所以嗰啲咩嘢八股文呀，朙月拼音呀都會一齊安裝埋，只不過唔係預設方案選單入面出現。

哦原來係噉，我唔知道使唔使喺個default入邊都加埋先可以反查，我而家測試下試下先

**Comment by laubonghaudoi** [comment]
@tanxpyox 啱啱重裝試咗下，感覺非常好，反查都冇問題。不過可能可以改一個地方，就係默認將個`menu_size`從 5 改成10，我估大家都會習慣用大啲嘅菜單

**Comment by tanxpyox** [comment]
:+1:  weasel-0.14.3.21-installer.exe 改好咗

**Comment by tiujejauci** [comment]
> @tanxpyox 啱啱重裝試咗下，感覺非常好，反查都冇問題，我以後就用你呢個封裝嘞。不過可能可以改一個地方，就係默認將個`menu_size`從 5 改成10，我估大家都會習慣用大啲嘅菜單。

menu_size呢個真係要跟默認，我試過去到8，我打字開始變慢咗，最後調到6

**Comment by tanxpyox** [comment]
呢個方案已經胎死腹中，唔會再有任何支援。而家 #56 研究緊一個可持續方案，請拭目以待。

**Comment by tiujejauci** [comment]
剷走 候選項目顯示：自己打錯之錯詞：

唔小心打錯詞，再打同樣拼音，錯詞一直喺候選欄，可以：
先用↑或↓掣揀中要剷走項目，
跟住撳 Shift+Delete 或 Control+Delete（蘋果鍵盤用 Shift+Fn+Delete）。

*剷走非自己打錯項目，只會調整詞彙顯示排序。
