### ISSUE TITLE
如果我唔識某一個字點打 係咪再嵌入一個拆字粵拼呀？

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#57]
睇到可以用V掣去用倉頡打字反查粵拼，但係我倉頡好屎，唔識打某一個字，有無拆字反查粵拼方法？

譬如：搜狗拼音輸入法：查「乪」字點打咁，撳 `U` + `yi` + `tian`，就可以出「乪」字。

呢個項目如果有得撳 `U` + `jim` + `tin`，就可以出「乪」字。咁樣咪仲好？

**Comment by laubonghaudoi** [comment]
目前Rime唔支持拆字查粵拼功能。如果想查粵拼，一唔係用README入邊講嘅普通話拼音、筆畫、倉頡嚟反查，一唔係就用 [jyut.net](https://jyut.net/) 呢個字典嚟查。

**Comment by tanxpyox** [comment]
如果你有興趣嘅話可以試下自己實裝，但係現階段我哋冇計劃新增呢個功能。

https://github.com/tanxpyox/rime-component

**Comment by tanxpyox** [comment]
暫時之係做到噉樣
![image](https://user-images.githubusercontent.com/9696140/81940388-20204500-962a-11ea-915a-cbd45885c40d.png)

**Comment by tanxpyox** [comment]
已經成功實裝：運行以下指令：
```sh
bash rime-install tanxpyox/rime-component:customize:schema=jyut6ping3 tanxpyox/rime-component-jyutping:install
```
然後使用 <kbd> r </kbd> + 粵拼碼即可造字
 ![image](https://user-images.githubusercontent.com/9696140/81950967-2c5ecf00-9637-11ea-9528-18ae83ee750b.png)

 ![image](https://user-images.githubusercontent.com/9696140/81951007-37b1fa80-9637-11ea-8930-58c0f244b01d.png)

亦支援聲調輸入，增加準確度
![image](https://user-images.githubusercontent.com/9696140/81951303-97100a80-9637-11ea-8098-c84d8c8cdb28.png)

部首輸入可用大衆讀音
![image](https://user-images.githubusercontent.com/9696140/81951622-f8d07480-9637-11ea-9b76-1ca6a49a71a1.png)

**Comment by tiujejauci** [comment]
> 已經成功實裝：運行以下指令：
> 
> ```shell
> bash rime-install tanxpyox/rime-component:customize:schema=jyut6ping3 tanxpyox/rime-component-jyutping:install
> ```
> 
> 然後使用 r  + 粵拼碼即可造字
> ![image](https://user-images.githubusercontent.com/9696140/81950967-2c5ecf00-9637-11ea-9528-18ae83ee750b.png)
> 
> ![image](https://user-images.githubusercontent.com/9696140/81951007-37b1fa80-9637-11ea-8930-58c0f244b01d.png)
> 
> 亦支援聲調輸入，增加準確度
> ![image](https://user-images.githubusercontent.com/9696140/81951303-97100a80-9637-11ea-8098-c84d8c8cdb28.png)
> 
> 部首輸入可用大衆讀音
> ![image](https://user-images.githubusercontent.com/9696140/81951622-f8d07480-9637-11ea-9b76-1ca6a49a71a1.png)

好似行錯咗方向。。。
正確示範：
查痧，
打beng saa
應該係顯示 痧（saa），
而唔係病沙。

**Comment by tiujejauci** [comment]
仲有想問下
`bash rime-install tanxpyox/rime-component:customize:schema=jyut6ping3 tanxpyox/rime-component-jyutping:install`
喺Windows環境下行唔行得通？

**Comment by tanxpyox** [comment]
> 應該係顯示
> `痧（saa）`，

你可以自己試下調整。代碼授權方式爲GPL v3.0。

> 喺Windows環境下行唔行得通？

可經git bash運行。詳見https://github.com/rime/plum 。

**Comment by tiujejauci** [comment]
來源：https://pinyin.sogou.com/help.php?list=3&q=8&f=CandHint&h=E1B284A815508743695EFED9939C6A11&v=7.5.0.5674&r=0000_sogou_pinyin_75h
二、拆分输入 

将一个汉字拆分成多个组成部分，u模式下分别输入各部分的拼音即可得到对应的汉字。如【林】字，可拆分为两个独立的【木】字： 
 ![image](https://user-images.githubusercontent.com/31369434/82394915-d8137f00-9a7c-11ea-8d41-bad0771e356c.png)

又如【曙】字，可以拆分成【日】【罒】和【者】，于是： 
 ![image](https://user-images.githubusercontent.com/31369434/82394921-dcd83300-9a7c-11ea-9f2d-2b9ffb52f76c.png)

也可以做部首拆分输入。如【氻】，可拆分为【 氵】和【力】 
 ![image](https://user-images.githubusercontent.com/31369434/82394927-e1045080-9a7c-11ea-8f63-1aa884108c17.png)

**Comment by tiujejauci** [comment]
> > 部首輸入可用大衆讀音
> > ![image](https://user-images.githubusercontent.com/9696140/81951622-f8d07480-9637-11ea-9b76-1ca6a49a71a1.png)
> 
行tanxpyox/rime-component:customize:schema=jyut6ping3 tanxpyox/rime-component-jyutping:install 實際效果
![image](https://user-images.githubusercontent.com/31369434/82395583-65a39e80-9a7e-11ea-900c-58530246ced8.png)

**Comment by tanxpyox** [comment]
要ctrl+` --> 2 啓動拆字模式
