### ISSUE TITLE
無聲母與ng聲母混淆

### ISSUE THREAD

**Issue by abemikako** [rime/rime-cantonese#58]
### 本人鄉下粵西，操廣府話，特點有嚴格區分無聲母與ng聲母，n同l等等

本人深悉廣州方言經已完全混淆無聲母及ng聲母，對於非漢語來源嘅音，利用韻書推測出未混淆前嘅音亦可能無能爲力。但係我嘅母語方言係嚴格區分兩者嘅，兩者完全互補，所以我旨在協助區分佢哋，係個人意見

本人意見非基於韻書，係基於本人由細長大時所接收到嘅發音

由於此issue需針對原碼表（May, 2020) 進行引用，故使用個人格式，敬請諒解
本人篩選原碼表時發現，大概有1,200個字屬於無聲母及或ng聲母，咁多字我只能得閒就檢查，同埋我相信要檢查嘅字重唔止呢啲

本issue收集本人對無聲母與ng聲母字嘅收音情況，列表未完成，歡迎交流及指正

**註**：接收音即本人於鄉長大時**接收到**嘅發音，非接收音即本人於鄉下長大時**未接收**到嘅發音

### 意見

| 字 | 碼表音 | 註釋 |
|----|----|:-------------------|
| 呃 | ngak1 | **接收音**。欺騙|
| 呃 | ngaak1 | 非接收音。欺騙|
| 呃 | ak1 | 非接收音。欺騙|
| 呃 | aak1 | 非接收音。欺騙|
| 哽 | ang2 | **接收音**。受硬物擠壓而受損|
| 哽 | ngang2 | 非接收音。受硬物擠壓而受損|
| 嚙 | ngaat6 | **接收音**。蟲、鼠類動物啃咬，有人會講 ngat6，感覺上更口語化|
| 嚙 | ngit6 | 文言？|
| 囓 | ngit6 | 同「嚙」|
| 囓 | ngaat6 | 同「嚙」|
| 壅 | ung1 | **接收音**。掩埋，無聲母|
| 壅 | jung2 | 非接收音。掩埋|
| 壅 | jung1 | 非接收音。掩埋|
| 孲 | aa1 | 非接收音。表示「嬰孩」用「ngaa1」，「ngaa4 ngaa1仔」，「ngaa1仔」。單字音依然係ngaa1，用作人名時依然係ngaa1，可能本字係「伢」，伢伢仔，伢伢，伢仔|
| 岰 | aau3 | **接收音**。山坳，同坳|
| 岰 | au3 | 非接收音。山坳，同坳|
| 幄 | ak1 | **接收音**。帷幄|
| 幄 | aak1 | 非接收音。帷幄|
| 戹 | ak1 | **接收音**。同厄|
| 戹 | aak1 | 非接收音。同厄|
| 扤 | ngaat6 | **接收音**。搖動|
| 扤 | ngat6 | **接收音**。搖動，常用|
| 扤 | at1 | 非接收音。廣州方言，按|
| 扤 | ngat1 | 非接收音。廣州方言之變音|
| 扼 | ak1 | **接收音**。漢語|
| 扼 | aak1 | 非接收音。漢語|
| 押 | aap3 | **接收音**|
| 押 | aat3 | **接收音**。漢語，常用|
| 挨 | ngaai4 | **接收音**。挨打，挨生挨死，同捱？|
| 挨 | aai1 | **接收音**。挨近|
| 挨 | oi2 | 非接收音|
| 握 | ak1 | **接收音**。漢語|
| 握 | aak1 | 非接收音|
| 擙 | ngou1 | **接收音**。向高處或遠處取物|
| 擙 | ou1 | 非接收音。向高處或遠處取物|
| 枒 | aa1 | **接收音**。樹丫|
| 枒 | ngaa4 | 木名，非樹丫|
| 枒 | ngaa1 | 非接收音。樹丫|
| 椏 | aa1 | **接收音**。丫之異體。分叉，分支。樹丫，丫頭，丫鬟，丫叉，枝丫|
| 椏 | ngaa6 | 非接收音。|
| 椏 | ngaa1 | 非接收音。樹丫|
| 熬 | ngou4 | **接收音**。漢語|
| 熬 | ngaau4 | 非接收音。漢語|
| 爊 | ou1 | **接收音**。爊熟|
| 爊 | ngou4 | 非接收音。爊熟|
| 爊 | ngaau4 | 非接收音。爊熟|
| 猗 | o2 | **接收音**。猗儺|
| 猗 | ngo5 | 非接收音。猗儺|
| 瓦 | ngaa5 | **接收音**。漢語|
| 瓦 | ngaa6 | 非接收音。漢語|
| 眲 | ngak1 | **接收音**。（借字），欺騙|
| 眲 | ngaak1 | 非接收音。（借字），欺騙|
| 睚 | ngaai4 | **接收音**。睚眥|
| 睚 | ngaai6 | 非接收音。睚眥|
| 矮 | ai2 | **接收音**。漢語|
| 矮 | aai2 | 非接收音。漢語|
| 碾 | zin2 | **接收音**。|
| 碾 | nin5 | **接收音**。碾壓，碾碎。又音ngaan4 （最常用），碾爛，碾米|
| 碾 | nin6 | 非接收音|
| 翱 | ngou4 | **接收音**。翱翔|
| 翱 | ngou6 | 非接收音。翱翔|
| 軛 | aak3 | **接收音**。牛軛|
| 軛 | aak2 | 非接收音。牛軛|
| 軛 | aak1 | 非接收音。牛軛|
| 軶 | aak3 | **接收音**。同軛|
| 軶 | aak1 | 非接收音。同軛|
| 軶 | ak1 | 非接收音。同軛|
| 鈪 | aak3 | **接收音**。鐲器|
| 鈪 | aak2 | 非接收音。鐲器|
| 鈪 | ngaak6 | 非接收音。鐲器|
| 鏖 | ou1 | **接收音**。鏖戰|
| 鏖 | ngou4 | 非接收音。鏖戰|
| 隘 | aai3 | **接收音**。漢語|
| 隘 | ai3 | 非接收音。漢語|
| 餲 | aat3 | 非接收音。尿臭味，ngaat3，有時ngat3|
| 𠼮 | ngai1 | **接收音**。懇求|
| 𠼮 | ai1 | 非接收音。懇求|
| 𡁏 | ngam1 | 待定，本人暫未明其義|
| 𡁏 | am1 | 待定，本人暫未明其義|
| 𡃀 | e4 | 待定|
| 𡃀 | nge4 | 待定|
| 𢯎 | ngaau1 | **接收音**。𢯎痕。可能爲「鉤（ngau1）」變異而來|
| 𢯎 | aau1 | 非接收音。𢯎痕|
| 擪 | ngaap3 | 本人對此音義無印象|
| 擪 | aap3 | 本人對此音義無印象|
| 唉 | aai6 | 本人暫未明其義|
| 唉 | ngaai6 | 本人暫未明其義|
| 咓 | ngaa5 | 本人暫未明其義|
| 咓 | aa5 | 本人暫未明其義|
| 姎 | ong1 | 本人暫未明其義|

**Comment by abemikako** [comment]
因爲漢語字嚴格遵守以下規律
陽聲調對應ng聲母
陰聲調對應無聲母

且因爲本人能力有限，碼表入邊有大量未識嘅字

所以漢語字唔使點討論，希望有人整理一份關於ng聲母及無聲母且可能屬於非漢語嘅音/字表，標示發音，借字，及釋義，本人會依此發表我嘅意見

**Comment by abemikako** [comment]
draft 

常用

翳	ngai3	憂愁，唔舒服
揞	am2	捂，揞實個傷口
扲	ngam4	掏，摸，扲荷包
罯	ap1	罯生草藥
噏	ngap1	隨口噏
岌	ngap6	上下摇晃，岌頭
漚	au3	將某物放置一段時間，使其發酵或變質
吽	ngau6	吽哣
掗	ngaa6	霸佔
嗌	aai3	大聲喊
啱	ngaam1	正確
晏	aan3	晏晝
拗	aau2	折彎，折斷
詏	aau3	爭辯
？	ngok6	抬頭
戇	ngong6	笨
蕹	ung3	蕹菜
奀	ngan1	瘦弱
䟴	ngan3	䠆腳
悒	ap1	心悒
屙	o1	屙屎
擁	ung2	推

**Comment by laubonghaudoi** [comment]
明白，所以你而家提供咗你鄉下嘅口音作爲參考信息。但係有咩修改意見呢？你想改邊度？

**Comment by laubonghaudoi** [comment]
已經參照意見將問題修復 https://github.com/rime/rime-cantonese/commit/10dd1efb29c0546400bbc47cfa9d0326479227e0
