### ISSUE TITLE
CIN 格式表格

### ISSUE THREAD

**Issue by ethanliu** [rime/rime-cantonese#64]
由於 OpenVanilla (已停止維護) 專案中的 jyuping.cin 已過於老舊，而已來源也已不存在。
因此想以 jyut6ping3.dict.yaml 來轉換格式，內容會更動的部份:

刪除字詞部份，僅保留單字
刪除單字使用頻率
刪除拼音空格，置第一欄
字詞於第二欄
補上 CIN 格式資訊，如 keyname, chardef

則轉換後的內容如下:

	%ename jyut6ping3
	%cname 粵拼
	%encoding UTF-8
	%selkey 1234567890
	%endkey 123456
	%keyname begin
	a a
	...
	6 6
	%keyname end
	%chardef begin
	a1	吖
	a3	啊
	aa1	㝞
	aa1	䃁
	aa1	丫
	...
	%chardef end

想請問標頭說明部份，除了格式轉換及來源的說明之外
是否建議完整保留原 jyut6ping3.dict.yaml 的說明?
或是有其他建議的放置的資訊?
謝謝

**Comment by tanxpyox** [comment]
詞庫資料在共享創意-姓名標示4.0國際協議之下發放，只要遵從發放條件，即可自由分享或修改。請參閱以下網址瞭解條款詳情：https://creativecommons.org/licenses/by/4.0/deed.zh_TW

審視上述說明，我建議除冒頭資訊外，應加入以下資訊：
1. 說明本詞庫在共享創意-姓名標示4.0國際協議之下發放 ；
2. 協議文本的連結 `http://creativecommons.org/licenses/by/4.0/`；和
3. 本詞庫的連結。
（詳見[此表](https://wiki.creativecommons.org/wiki/License_Versions#Detailed_attribution_comparison_chart)右欄）

此外，請小心字庫充斥大量生僻字，移除配詞、使用頻率等資訊將字庫直接用於輸入法恐怕表現不盡人意。

**Comment by laubonghaudoi** [comment]
@tanxpyox 我哋嘅碼表字音仲未徹底審覈過，就噉用真係冇問題？

@ethanliu 請問攞呢個字音係用嚟做乜嘅呢？我哋碼表嘅單字音仲未經過最終審覈，直接用嚟做輸入法可能會有問題（尤其係刪晒啲字頻），如果可以嘅話最好加埋個詞庫同詞頻。另外敬請關注我哋嘅後續更新，會對字音同詞庫做好大嘅修正。

**Comment by tanxpyox** [comment]
> 我哋嘅碼表字音仲未徹底審覈過，就噉用真係冇問題？

呢曾真係要睇佢點用，但係其實我地個字表都主要係喺LSHK個字表度搵過嚟，問題應該會喺收多而唔係收錯，對於輸入法嚟講影響唔大。（但其實OpenVanilla原本個字表都係LSHK度嚟，所以我唔知到底佢想攞個字表嚟做咩 :confused: ）

不過既然係開放授權，佢攞嚟點用我地到控制唔到。

**Comment by ethanliu** [comment]
謝謝。來源、授權我也覺得不可少。
但因格式轉換，特別是會刪去某些資料，所以與原始的說明會有差別之外，也怕有誤導，但 credit 肯定是不能少。

抱歉我不會說粵語 (所以我也不是粵拼使用者)，所以希望沒有誤解意思。

CIN 格式及傳統的輸入法，沒有含詞頻，只有拆法(字根)及字/詞，二項資料
優先順序即是依編排的順序，所以格式上仍須刪除。
但如果能參考詞頻來調整順序，或許會比直接刪除來的好。

重複的字詞應不影響輸入法，因為一般輸入法還是會過濾掉重複或是以第一個為優先。如果有這疑慮，我想我也可以轉換時做些測試，是否有重複的字詞。

OV 使用的粵拼表格，依資訊來看也的確也是取 LSHK 詞庫，但版本停留在 2000/2001 之間，所以僅含一萬多字也已無維護，而 rime 這裡維護的版本單字即有三萬多字。

一旦有轉換後公開釋出的 CIN 版本，也會盡量跟上 rime 版本的更新

**Comment by laubonghaudoi** [comment]
@tanxpyox 我哋個字表同 LSHK 字表有啲收字同收音上嘅原則差異，最重要嘅兩個區別就係 1. LSHK 字表有收簡體字，我哋清晒啲簡體字，凈係保留異體字，將簡化交畀 OpenCC 處理。2. LSHK 字表唔區分疑影，我哋區分，即係喺 LSHK 字表基礎上刪晒啲疑影混淆嘅讀音。

@ethanliu 感謝你的貢獻，所謂三萬多個只是單字音數量，因爲有很多字都是多音字，所以只算字形的話只有兩萬多個漢字字的發音。我沒用過 OpenVanilla 的粵拼輸入法，請問發佈後能否提供一個安裝使用教程讓我們也體驗一下，提供使用反饋？

**Comment by ethanliu** [comment]
不客氣，我只是做個格式轉換，真正辛苦的才是你們。 
OpenVanilla/Yahoo!KeyKey 雖都已停止維護，不過應該是都還夠安裝使用，請待我稍後試試看。
如果你們也有意願測試，是再好不過的。

目前參考詞頻，整理後的順序會像這樣。
請問 0% 是否應該同等於無指定詞頻，所以順序沒有變動。或是實際上 0% 會有所差別?

	aai1	噯	#0.03
	aai1	劸
	aai1	哎
	aai1	唉
	aai1	唲
	aai1	埃
	aai1	娭
	aai1	挨
	aai1	溾
	aai2	欸
	aai2	毐
	aai3	呃	#0.03
	aai3	噫	#0.03
	aai3	阨	#0.03
	aai3	㿄
	aai3	䅬
	aai3	伌
	aai3	唉
	aai3	嗄
	aai3	嗌
	aai3	塧
	aai3	砨
	aai3	賹
	aai3	阸
	aai3	隘
	aai3	餲
	aai6	唉	#0.03

另外我也測試過單字及詞彙是否有重複，jyut6ping3.dict.yaml 裡
單字部份沒有問題，詞彙則僅只有 138111，138112 二筆是重複的同詞同音。

	屋契	uk1 kai3
	屋漏兼逢夜雨	uk1 lau6 gim1 fung4 je6 jyu5

**Comment by laubonghaudoi** [comment]
@ethanliu 不是，標記 0% 代表這個字是生僻字或者這個發音是罕見音，所以在輸入法候選項排序時會排到最後。如果去除這些 0% 標記，可能會導致輸入法把這些生僻字或生僻音都排在首選項，嚴重影響打字體驗。

**Comment by ethanliu** [comment]
因為 rime 文件上有說明詞頻不會有負數，但並沒有特別說明 0% 是否另外作用，感謝說明。
同一段重新排序後的結果，比對用注釋 #300 為 3%, #10 為 0% 

	aai1	噯	#300
	aai1	哎
	aai1	唉
	aai1	唲
	aai1	埃
	aai1	挨
	aai1	溾
	aai1	劸	#10
	aai1	娭	#10
	aai2	欸
	aai2	毐	#10
	aai3	呃	#300
	aai3	噫	#300
	aai3	阨	#300
	aai3	㿄
	aai3	䅬
	aai3	唉
	aai3	嗌
	aai3	賹
	aai3	隘
	aai3	餲
	aai3	伌	#10
	aai3	嗄	#10
	aai3	塧	#10
	aai3	砨	#10
	aai3	阸	#10
	aai6	唉	#300

因為先前好像有提到可能有重複的部份，所以簡單比對後 (BBEdit Duplicate lines 功能)
詞彙部份僅有 138111，138112 二行是重複的。

**Comment by tanxpyox** [comment]
> 因為先前好像有提到可能有重複的部份，所以簡單比對後 (BBEdit Duplicate lines 功能)
> 詞彙部份僅有 138111，138112 二行是重複的。

謝謝，我們正在整理詞表的錯音問題，完成整理後會一拼處理重複收錄的問題。

**Comment by laubonghaudoi** [comment]
@ethanliu 我們剛剛更新了碼表，已經修復了錯音問題並且去重排序。

**Comment by ethanliu** [comment]
謝二位告知。
新的碼表我另有發現詞頻格式(有些非使用%)及詞彙重複的問題，
會建議我另開新 issue 或是這篇直接提就好?

**Comment by tanxpyox** [comment]
這裏就可以了

**Comment by laubonghaudoi** [comment]
> 謝二位告知。
> 新的碼表我另有發現詞頻格式(有些非使用%)及詞彙重複的問題，
> 會建議我另開新 issue 或是這篇直接提就好?

 不使用%是不是指在後面加10000的那些詞？那是代表高頻詞，相同音節輸入下，把這種詞排在最前面。另外詞彙重複具體是什麼？我們已經做過去重，不應該會有詞彙重複，只會有相同詞彙不同發音，即多音詞。

**Comment by ethanliu** [comment]
高詞頻的部份瞭解，所以 rime 應該是等同 10000% 這樣的處理方式。
詞彙重複的部份有二種，都是同詞同音

直接重複的

    稟神	ban2 san4
    稟神	ban2 san4
    稟神都冇句真	ban2 san4 dou1 mou5 geoi3 zan1
    稟神都冇句真	ban2 san4 dou1 mou5 geoi3 zan1
    邊個	bin1 go3
    邊個	bin1 go3
    邊啲	bin1 di1
    邊啲	bin1 di1
    乒嘭	bing4 baang4
    乒嘭	bing4 baang4
    伏匿匿	buk6 nei1 nei1
    伏匿匿	buk6 nei1 nei1
    鑔鑔	caa4 caa2
    鑔鑔	caa4 caa2
    閪嘢	hai1 je5
    閪嘢	hai1 je5
    綳綳緊	maang1 maang1 gan2
    綳綳緊	maang1 maang1 gan2
    阿茂整餅	aa3 mau6 zing2 beng2
    阿茂整餅	aa3 mau6 zing2 beng2
    呢個	nei1 go3
    呢個	nei1 go3

同時有一筆有詞頻，一筆無詞頻的

    大粒	daai6 lap1	0%
    大粒	daai6 lap1
    但係	daan6 hai6	10000.0
    但係	daan6 hai6
    點知	dim2 zi1	10000.0
    點知	dim2 zi1
    都得	dou1 dak1	10000.0
    都得	dou1 dak1
    噉樣	gam2 joeng2	10000.0
    噉樣	gam2 joeng2
    嘰屹	gi1 gat6	5%
    嘰屹	gi1 gat6
    嗰個	go2 go3	10000.0
    嗰個	go2 go3
    嗰陣	go2 zan6	1000.0
    嗰陣	go2 zan6
    喺度	hai2 dou6	10000.0
    喺度	hai2 dou6
    好鬼死	hou2 gwai2 sei2	10000.0
    好鬼死	hou2 gwai2 sei2
    一齊	jat1 cai4	1000.0
    一齊	jat1 cai4
    有冇	jau5 mou5	10000.0
    有冇	jau5 mou5
    肉粒	juk6 lap1	0%
    肉粒	juk6 lap1
    原子粒	jyun4 zi2 lap1	0%
    原子粒	jyun4 zi2 lap1
    佢哋	keoi5 dei6	10000.0
    佢哋	keoi5 dei6
    粒粒	lap1 lap1	0%
    粒粒	lap1 lap1
    我哋	ngo5 dei6	10000.0
    我哋	ngo5 dei6
    先至	sin1 zi3
    先至	sin1 zi3	1000.0
    真係	zan1 hai6	10000.0
    真係	zan1 hai6
    仲係	zung6 hai6	1000.0
    仲係	zung6 hai6

**Comment by ethanliu** [comment]
再次感謝二位的幫忙
此為使用 jyut6ping3.dict.yaml 轉換的 cin 表格及字詞 csv 

[jyut6ping3-toneless.cin](https://github.com/ethanliu/OkidoKeyCharsets/blob/v2.1/table/jyut6ping3-toneless.cin)
[jyut6ping3.cin](https://github.com/ethanliu/OkidoKeyCharsets/blob/v2.1/table/jyut6ping3.cin)
[Rime-cantonese.csv](https://github.com/ethanliu/OkidoKeyCharsets/blob/v2.1/lexicon/Rime-cantonese.csv)
[Rime-cantonese.csv.txt](https://github.com/ethanliu/OkidoKeyCharsets/blob/v2.1/lexicon/Rime-cantonese.csv.txt)


cin 表格在 macOS 的使用方式

至 [OV 官網](https://openvanilla.org) 下載並安裝完成後，OpenVanilla 應會自動出現在輸入法鍵盤中
若未出現，可再於系統設定/鍵盤/輸入法，再新增 OpenVanilla

![System Preference / Keyboard](https://www.dropbox.com/s/n90qmfhye23bdhr/ov-01.png?raw=1)

鍵盤切換至 OpenVanilla 後，再點一次輸入法圖示，即可開啟輸入法選單，再選擇 OpenVanilla 偏好設定…

![OV Menu](https://www.dropbox.com/s/5gzujafo1bbf2cq/ov-02.png?raw=1)

OV 有內建粵拼，但為較舊的版本
選擇新增輸入法後，再匯入 jyut6ping3.cin 或 jyut6ping3-toneless.cin

![OV Preference](https://www.dropbox.com/s/cyws88tdc7l19im/ov-03.png?raw=1)

匯入完成後，點選新增的 Jyut6ping3 項目，可再做一些基本的輸入法偏好設定

![OV Preference](https://www.dropbox.com/s/i4ts8oqljmezblm/ov-04.png?raw=1)

完成設定後再開啟 OV 輸入法選單，即可選擇新增的 Jyut6ping3 輸入法

![OV Menu](https://www.dropbox.com/s/5gzujafo1bbf2cq/ov-02.png?raw=1)

使用畫面

![Sample](https://www.dropbox.com/s/3czjkjr68cxg2hb/ov-05.png?raw=1)

macOS 直接就有支援 cin 格式，所以也可以直接使用

![](https://www.dropbox.com/s/ddcmcmedrqrhei8/ov-10.png?raw=1)

開啟後，不會有什麼訊息，點選鍵盤選項就會有剛剛新增的輸入法

![Insatall](https://www.dropbox.com/s/3j8a2clq9xx91tv/ov-11.png?raw=1)

內建的支援無其他功能設定，所以輸入時需要每次按下空白鍵，才會出現候選字

![Sample](https://www.dropbox.com/s/s74cxu9ofeulh2j/ov-12.png?raw=1)

另外粵拼也會使用在我的 iOS 平台的輸入法 app
分開為輸入法與詞庫使用，在安裝前會有相關的說明，及 cin 標頭的內容或字詞另外的說明文件內容

![iOS-cin](https://www.dropbox.com/s/mocwgcqgrc8qu54/ios-01.png?raw=1)
![iOS-phrase](https://www.dropbox.com/s/0l37pbojlzqczbm/ios-02.png?raw=1)

**Comment by tanxpyox** [comment]
感謝幫忙

**Comment by laubonghaudoi** [comment]
@ethanliu 謝謝！請問有沒有辦法把這個最新版的rime-cantonese碼表直接加入OV的默認安裝自帶碼表中呢？現在安裝完之後還是要自己 import 碼表，比較麻煩。我們希望能做成一個即裝即用的粵拼輸入法。

**Comment by ethanliu** [comment]
已詢問 OV 同意
若接下來一些測試都沒有問題後，會再討論一下方式(與現行內建的粵拼)
我會再提交給 OV

**Comment by laubonghaudoi** [comment]
@ethanliu 請問最近 OV 那邊有沒有更新呢？

**Comment by ethanliu** [comment]
@laubonghaudoi 我也是看目前異動比較頻繁所以尚未提交，那我就來著手處理，感謝告知。
