### ISSUE TITLE
rime小狼毫0.9.x 中文打字模式-粵拼方案 可以打密碼，𠵱家新版本反而唔得？

### ISSUE THREAD

**Issue by tiujejauci** [rime/rime-cantonese#67]
![圖片](https://user-images.githubusercontent.com/31369434/84039449-d4b44900-a9d3-11ea-9610-a1462fe6070b.png)
![圖片](https://user-images.githubusercontent.com/31369434/84039497-e5fd5580-a9d3-11ea-8743-52a2caadd577.png)

請問是否配置問題？

**Comment by tanxpyox** [comment]
小狼毫喺輸入嘅時候會喺輸入欄入面 **暫時** 加入一個空格。撳<kbd>space</kbd> 或者 <kbd> enter</kbd> 嚟完成輸入之後空格會消失。

**Comment by tiujejauci** [comment]
> 小狼毫喺輸入嘅時候會喺輸入欄入面 **暫時** 加入一個空格。撳space 或者 enter 嚟完成輸入之後空格會消失。

即係。。每撳一次字母就要撳一次space 或者 enter？

**Comment by tiujejauci** [comment]
https://github.com/rime/weasel/issues/182#issue-312741760

**Comment by laubonghaudoi** [comment]
呢個屬於小狼毫嘅問題，唔關我哋 rime-cantonese 事，要去 https://github.com/rime/weasel/issues 提出

**Comment by tanxpyox** [comment]
> 即係。。每撳一次字母就要撳一次space 或者 enter？

唔係。打哂成抽再撳enter都得。

1. 輸入`onetwo` (例)
![image](https://user-images.githubusercontent.com/9696140/84100886-5b524000-aa3f-11ea-882d-4836000c09b7.png)

2. 拍 <kbd> enter </kbd> ， 出現6個字符。檢查完成。
![image](https://user-images.githubusercontent.com/9696140/84100966-889eee00-aa3f-11ea-831a-5dfc502bd7d9.png)

**Comment by tiujejauci** [comment]
> > 即係。。每撳一次字母就要撳一次space 或者 enter？
> 
> 唔係。打哂成抽再撳enter都得。
> 
> 1. 輸入`onetwo` (例)
>    ![image](https://user-images.githubusercontent.com/9696140/84100886-5b524000-aa3f-11ea-882d-4836000c09b7.png)
> 2. 拍  enter  ， 出現6個字符。檢查完成。
>    ![image](https://user-images.githubusercontent.com/9696140/84100966-889eee00-aa3f-11ea-831a-5dfc502bd7d9.png)

唔係，曾係bug嚟 口架（打唔出），唯有撳`shift`掣打密碼，𠵱家無啦啦又得咗喎。

**Comment by tanxpyox** [comment]
> 𠵱家無啦啦又得咗喎

無問題嘅話我就閂咗呢個issue佢嘞。
