### ISSUE TITLE
「鱟地坊」

### ISSUE THREAD

**Issue by tanxpyox** [rime/rime-cantonese#68]
![MVIMG_20200607_180932](https://user-images.githubusercontent.com/31369434/84037595-6c7a4e80-a964-11ea-87f9-3fabbb5699ca.jpg)
![IMG_20200608_021656](https://user-images.githubusercontent.com/31369434/84037647-7ac86a80-a964-11ea-9e0a-6cdd1d11cd99.JPG)
請求增加「[鱟地坊](https://zh.wikipedia.org/zh-hk/%E9%B1%9F%E5%9C%B0%E5%9D%8A)」

_Originally posted by @tiujejauci in https://github.com/rime/rime-cantonese/issues/28#issuecomment-640613558_

**Comment by tanxpyox** [comment]
@tiujejauci 下次回報詞條問題請用[呢個](https://github.com/rime/rime-cantonese/issues/new?assignees=&labels=&template=------.md&title=)範本嚟開一個**新**嘅issue，方便追蹤。

**Comment by tiujejauci** [comment]
> @tiujejauci 下次回報詞條問題請用[呢個](https://github.com/rime/rime-cantonese/issues/new?assignees=&labels=&template=------.md&title=)範本嚟開一個**新**嘅issue，方便追蹤。

明白。。。
