### ISSUE TITLE
iOS端iRime輸入法無法導入粵拼詞庫

### ISSUE THREAD

**Issue by PakTo** [rime/rime-cantonese#72]
### 問題描述

iOS端iRime輸入法電腦互傳並部署之後，點擊選擇方案，列表中無法找到粵語方案

**Comment by tanxpyox** [comment]
有冇更新 `default.custom.yaml`?
https://github.com/rime/rime-cantonese/wiki/iOS-%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B#6-%E6%90%B5-defaultcustomyaml-%E6%96%87%E4%BB%B6%E4%B8%A6%E4%B8%8B%E8%BC%89%E8%90%BD%E5%9A%9F%E5%A6%82%E6%9E%9C%E5%86%87%E5%98%85%E8%A9%B1%E5%B0%B1%E8%B7%B3%E9%81%8E%E5%91%A2%E5%80%8B%E6%AD%A5%E9%A9%9F%E8%87%AA%E5%B7%B1%E6%96%B0%E5%BB%BA

**Comment by PakTo** [comment]
更新咗了，照住個流程部署完仲係唔得

**Comment by laubonghaudoi** [comment]
如果實在唔得嘅話，可以裝搜狗粵拼用，下載搜狗輸入法iOS版入邊有得揀「中文-粵語」，就係我哋嘅 rime-cantonese改過來嘅。

**Comment by PakTo** [comment]
OK，冇問題
