### ISSUE TITLE
Unable to set up ibus-rime with cantonese input properly

### ISSUE THREAD

**Issue by p2635** [rime/rime-cantonese#83]
### 問題描述

As I am a 傻瓜beginner, I tried to use the `ibus-install.sh` script but I can't see Cantonese input method in my ibus-rime. Before I started, I already had ibus-rime installed and also librime-data-jyutping. I don't know what is wrong so my search led me to this repo and I tried to use the script as mentioned above.

Script Output:
```
pc:~/Downloads$ ./ibus-install.sh
Installing IME files ...
bash: line 17: git: command not found
bash: line 22: plum/rime-install: No such file or directory
Done!
pc:~/Downloads$ 
```

**What I see on my rime**
Where is my cantonese input?
![rime](https://user-images.githubusercontent.com/4522927/90333076-8b2b4000-dfba-11ea-9dd7-99434cd273c5.gif)

**Comment by tanxpyox** [comment]
Hi, may I know your platform/OS? I think it is because you haven't installed `git` (which should be pre-installed in Ubuntu and Pop OS distros iirc)

On Ubuntu/Pop_OS, it's simply:
```sh
sudo apt-get install git
```

**Comment by p2635** [comment]
@tanxpyox , 多謝你呀！問提解決咗。 I'm on Kubuntu 20.04 but installing git fixed it.

I think it may be worth updating the script to install curl or git if the system doesn't have it.

**Comment by tanxpyox** [comment]
:O The script should be installing `curl`, `git` and `ibus-rime` at line 10...

Did it return any error?

**Comment by p2635** [comment]
my dumb mistake, I actually removed that before I ran the script because I only saw 'ibus-rime' I thought I already got it installed so I don't need that line. But I missed curl and git.

**Comment by laubonghaudoi** [comment]
@tanxpyox 睇嚟要喺安裝教程嗰度加一步嗌啲人裝 git，我原先以為用得 linux 嘅人都會識得 git，睇嚟唔係。

**Comment by tanxpyox** [comment]
> @tanxpyox 睇嚟要喺安裝教程嗰度加一步嗌啲人裝 git，我原先以為用得 linux 嘅人都會識得 git，睇嚟唔係。

睇漏眼啫，應該不成問題。行嗰個script嘅時候應該會裝晒啲prerequisite嘅

**Comment by laubonghaudoi** [comment]
我好似見到唔止一個人都係因為冇git所以唔識裝，不過plum本身應該係將git當dependency嚟裝嘅，唔知點解plum冇裝到git

**Comment by p2635** [comment]
應該唔使啩, 係我自己搞錯咗 like @tanxpyox  said

I'll leave it up to you guys, I am thankful I found this input method though. Keep up the good work.
