### ISSUE TITLE
Why does my English look weird?

### ISSUE THREAD

**Issue by p2635** [rime/rime-cantonese#85]
If I try to type in English (while having Rime on), it sometimes appears like longer, is it called full width? I am trying to reproduce it now but it actually isn't working, it's all fine but occasionally it happens and I can't get rid of it. I have to switch from Rime to my normal 'English' keyboard.

**Comment by laubonghaudoi** [comment]
冇錯，係因為你開咗全角，即係呢度
![image](https://user-images.githubusercontent.com/11172180/90354765-14646600-dfff-11ea-9941-7ffb8e09e7cd.png)
撳<kbd>ctrl</kbd>+<kbd>`</kbd>再撳2就會出上面呢個選單，然後就可以校返半角

**Comment by p2635** [comment]
thanks, I'm sure it turned on itself randomly and not sure how it happened. At least I can fix it now.

By the way, ctrl + ` does nothing for me. Maybe it's keyboard dependant, I have to do F4.

**Comment by tanxpyox** [comment]
On Windows, pressing Ctrl + space will toggle between full-width and half-width characters.. idk if it'll work for you tho

**Comment by p2635** [comment]
That was the problem, thanks @tanxpyox
