### ISSUE TITLE
curl failed to verify the legitimacy of the server

### ISSUE THREAD

**Issue by p2635** [rime/rime-cantonese#86]
### 問題描述

Trying to follow the windows install:
https://github.com/rime/rime-cantonese/wiki/Windows-%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B

After step 2, I get this.

```
Rime package installer

Working directory: C:\Users\NAME\Downloads\weasel-0.14.3.0-installer.exe
Package installer directory: C:\Program Files (x86)\Rime\weasel-0.14.3\
Download cache directory: C:\Users\NAME\AppData\Local\Temp
Rime user directory: C:\Users\NAME\AppData\Roaming\Rime

Enter package name, URL, user/repo or downloaded ZIP to install: cantonese
Downloading rime-install ...
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

Installation failed: Error downloading rime-install
```

**Comment by tanxpyox** [comment]
:O I was also getting this problem with my server in Arizona - but it seems to work fine elsewhere. Sadly, I don't think there's a way to fix it without changing the code... Maybe you can try asking the devs over at [rime/plum](https://www.github.com/rime/plum) and see if they can help

**Comment by p2635** [comment]
Is there a way I can download a zip or something and just point at the zip? @tanxpyox

**Comment by laubonghaudoi** [comment]
@p2635 睇[Windows 進階安裝教程](https://github.com/rime/rime-cantonese/wiki/Windows-%E9%80%B2%E9%9A%8E%E5%AE%89%E8%A3%9D%E6%95%99%E7%A8%8B)，呢個下載過程同你手動複製粘貼啲yaml文件係一樣嘅，複製粘貼咗啲文件之後去個default.yaml嗰度加個`jyut6ping3`落schema嗰度就得。具體可以去telegram用戶羣入邊問

**Comment by tanxpyox** [comment]
[`windows-*-installer.zip`](https://github.com/rime/rime-cantonese/releases/) should contain everything you need

> 點解好似冇咗個手動複製粘貼 yaml 文件部署嘅教程？我記得我以前寫過一個嘅
係咩？我冇印象喎

**Comment by p2635** [comment]
@tanxpyox @tanxpyox manual copy worked, 搞掂咗. 多謝你哋咁快覆我!
