### ISSUE TITLE
匯入英文維基詞典啲發音

### ISSUE THREAD

**Issue by szc126** [rime/rime-cantonese#88]
已有 [CBOR 格式](https://en.wikipedia.org/wiki/CBOR)嘅 [dump](https://tools-static.wmflabs.org/templatehoard/dump/latest/zh-pron.cbor)（[about](https://tools-static.wmflabs.org/templatehoard/dump/)）。

parameter `c` 爲標準粵語嘅發音、`/` 爲 delimiter、`-` 爲變調符號，等於 Cantodict 嘅 `*`。

parameter `c_note` 爲發音註釋。

~（而家唔推薦加單字，有啲係 unicode 或者《漢語多功能字庫》抄翻嚟嘅。）~ 嗯，無所謂啦，畢竟rime-cantonese個詞典都已經係噉

**Comment by laubonghaudoi** [comment]
可唔可以直接開個PR入嚟？

**Comment by szc126** [comment]
@laubonghaudoi [腳本](https://github.com/szc126/rime-cantonese/blob/build-enwt/enwiktionary.py)做好咗，唔明你哋係點統合啲數據嘅。

**Comment by laubonghaudoi** [comment]
你先新開個 yaml 文件，好似個地名噉，畀我哋睇下個效果點，改好咗再 merge 入嚟。

**Comment by szc126** [comment]
:+1: 已up咗 jyut6ping3.enwiktionary.*.txt（非yaml）。~暫時懶得整成個yaml嚟試用~

**Comment by szc126** [comment]
OK，試咗，冇問題。
