### ISSUE TITLE
Using the repository as a jyutping dictionary in python

### ISSUE THREAD

**Issue by tshmak** [rime/rime-cantonese#97]
Hi, 

Is it possible to use your repository as a jyutping dictionary in python? If so, any instructions on how to go about this? 

Many thanks, 

Tim

**Comment by ayaka14732** [comment]
[CanCLID/ToJyutping](https://github.com/CanCLID/ToJyutping)

**Comment by tshmak** [comment]
Are your sources also released under CC-BY ? Or is it your software only?

**Comment by tanxpyox** [comment]
Like which one? Source codes in this repo are just scripts for cleaning the dictionary / packing the files into archives

**Comment by sgalal** [comment]
@tanxpyox We should clarify in our README that `jyut6ping3.maps` is licensed under the Open Data Commons Open Database License (ODbL).

**Comment by tanxpyox** [comment]
Agreed. Would you do the honours?

**Comment by ayaka14732** [comment]
> Agreed. Would you do the honours?

Fixed in https://github.com/rime/rime-cantonese/commit/586206e99ddc909b751914300cd88b7ee52a7a7e

**Comment by sgalal** [comment]
> Agreed. Would you do the honours?

Done in https://github.com/rime/rime-cantonese/commit/586206e99ddc909b751914300cd88b7ee52a7a7e
